<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE LIGO_LW [
<!ELEMENT LIGO_LW ((LIGO_LW|Comment|Param|Table|Array|Stream|IGWDFrame|AdcData|AdcInterval|Time|Detector)*)>
<!ATTLIST LIGO_LW
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Comment (#PCDATA)>

<!ELEMENT Param (#PCDATA|Comment)*>
<!ATTLIST Param 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED
         Unit CDATA #IMPLIED
         DataUnit CDATA #IMPLIED>

<!ELEMENT Table (Comment?,Column*,Stream?)>
<!ATTLIST Table 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Column EMPTY>
<!ATTLIST Column
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Array (Dim*,Stream?)>
<!ATTLIST Array 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Dim (#PCDATA)>
<!ATTLIST Dim 
         Name  CDATA #IMPLIED
         Unit CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED>

<!ELEMENT Stream (#PCDATA)>
<!ATTLIST Stream 
         Name      CDATA #IMPLIED
         Type      (Remote|Local) "Local"
         Delimiter CDATA ","
         Encoding  CDATA #IMPLIED
         Content   CDATA #IMPLIED>

<!ELEMENT IGWDFrame ((Comment|Param|Time|Detector|AdcData|LIGO_LW|Stream?|Array|IGWDFrame)*)>
<!ATTLIST IGWDFrame 
         Name CDATA #IMPLIED>

<!ELEMENT Detector ((Comment|Param|LIGO_LW)*)>
<!ATTLIST Detector 
         Name CDATA #IMPLIED>

<!ELEMENT AdcData ((AdcData|Comment|Param|Time|LIGO_LW|Array)*)>
<!ATTLIST AdcData 
         Name CDATA #IMPLIED>

<!ELEMENT AdcInterval ((AdcData|Comment|Time)*)>
<!ATTLIST AdcInterval 
         Name CDATA #IMPLIED
         StartTime CDATA #IMPLIED
         DeltaT CDATA #IMPLIED>

<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time 
         Name CDATA #IMPLIED
         Type (GPS|Unix|ISO-8601) "ISO-8601">
]>

<LIGO_LW>
   <Comment>metadata</Comment>
   <Table Name="processgroup:process:table">
      <Column Name="processgroup:process:program" Type="lstring"/>
      <Column Name="processgroup:process:version" Type="lstring"/>
      <Column Name="processgroup:process:cvs_repository" Type="lstring"/>
      <Column Name="processgroup:process:cvs_entry_time" Type="int_4s"/>
      <Column Name="processgroup:process:comment" Type="lstring"/>
      <Column Name="processgroup:process:is_online" Type="int_4s"/>
      <Column Name="processgroup:process:node" Type="lstring"/>
      <Column Name="processgroup:process:username" Type="lstring"/>
      <Column Name="processgroup:process:unix_procid" Type="int_4s"/>
      <Column Name="processgroup:process:start_time" Type="int_4s"/>
      <Column Name="processgroup:process:end_time" Type="int_4s"/>
      <Column Name="processgroup:process:jobid" Type="int_4s"/>
      <Column Name="processgroup:process:domain" Type="lstring"/>
      <Column Name="processgroup:process:ifos" Type="lstring"/>
      <Column Name="processgroup:process:process_id" Type="ilwd:char"/>
      <Stream Name="processgroup:process:table" Type="Local" Delimiter=",">
         "sire","1.15","/usr/local/cvs/lscsoft/lalapps/src/inspiral/sire.c\,v",769623277," ",0,"ldas-grid.ligo.caltech.edu","dbrown",2163,776379284,776379284,0,"lalapps","","process:process_id:0"
      </Stream>
   </Table>
   <Table Name="process_paramsgroup:process_params:table">
      <Column Name="process_paramsgroup:process_params:program" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:process_id" Type="ilwd:char"/>
      <Column Name="process_paramsgroup:process_params:param" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:type" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:value" Type="lstring"/>
      <Stream Name="process_paramsgroup:process_params:table" Type="Local" Delimiter=",">
         "sire","process:process_id:0","--playground-only","string"," ",
         "sire","process:process_id:0","--input","string","h2-inca_l1h2.files",
         "sire","process:process_id:0","--output","string","h2-inca_l1h2.xml",
         "sire","process:process_id:0","--summary-file","string","h2-inca_l1h2.txt",
         "sire","process:process_id:0","--debug-level","string","33"
      </Stream>
   </Table>
   <Table Name="sngl_inspiralgroup:sngl_inspiral:table">
      <Column Name="sngl_inspiralgroup:sngl_inspiral:process_id" Type="ilwd:char"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ifo" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:search" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:channel" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_gmst" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:template_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:event_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:amplitude" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eff_distance" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:coa_phase" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass1" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mchirp" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eta" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau4" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau5" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ttotal" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:f_final" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:snr" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq_dof" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:sigmasq" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:alpha" Type="real_4"/>
      <Stream Name="sngl_inspiralgroup:sngl_inspiral:table" Type="Local" Delimiter=",">
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,427001953,1.2169739837451942e+01,729483825,427001953,2.2561180114746094e+01,1.7089843750000000e-03,0.000000e+00,1.369109e-01,-8.058608e-01,6.785972e-01,1.868759e-01,2.981594e-01,1.693005e-01,2.256838e+01,9.786729e-01,6.076915e-01,2.695146e-02,0.000000e+00,2.296631e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.938828e+00,5.350935e+01,15,1.8515967903424804e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,427978515,1.2169740106405483e+01,729483825,427978515,2.2570577621459961e+01,1.7089843750000000e-03,0.000000e+00,1.280791e-01,1.746328e+00,6.782500e-01,1.868698e-01,2.980864e-01,1.693466e-01,2.257759e+01,9.788525e-01,6.076915e-01,2.694989e-02,0.000000e+00,2.297570e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.062200e+01,4.515686e+01,15,1.8508409102031920e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,428222656,1.2169740173646973e+01,729483825,428222656,2.2579971313476562e+01,9.7656250000000000e-04,0.000000e+00,1.258689e-01,3.115804e+00,6.779031e-01,1.868637e-01,2.980134e-01,1.693927e-01,2.258681e+01,9.790319e-01,6.076915e-01,2.694833e-02,0.000000e+00,2.298510e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.080631e+01,4.089378e+01,15,1.8500856299687760e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,429443359,1.2169740509837865e+01,729483825,429443359,2.2585145950317383e+01,9.7656250000000000e-04,0.000000e+00,1.319070e-01,-1.834177e+00,5.773944e-01,2.134127e-01,2.984019e-01,1.970388e-01,2.253782e+01,9.465197e-01,5.545129e-01,2.500264e-02,0.000000e+00,2.295483e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.032285e+01,4.595533e+01,15,1.8541075922019792e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,429687500,1.2169740577079356e+01,729483825,429687500,2.2589363098144531e+01,1.4648437500000000e-03,0.000000e+00,1.432364e-01,2.047600e-01,6.775565e-01,1.868577e-01,2.979405e-01,1.694387e-01,2.259602e+01,9.792114e-01,6.076915e-01,2.694676e-02,0.000000e+00,2.299449e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.494106e+00,5.525578e+01,15,1.8493319494806866e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,430664062,1.2169740857241882e+01,729483825,430664062,2.2594552993774414e+01,1.4648437500000000e-03,0.000000e+00,1.393922e-01,1.086170e+00,5.770661e-01,2.134177e-01,2.983287e-01,1.970925e-01,2.254704e+01,9.466996e-01,5.545129e-01,2.500148e-02,0.000000e+00,2.296422e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.766526e+00,5.184262e+01,15,1.8533495124114918e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,431152343,1.2169740991716584e+01,729483825,431152343,2.2603942871093750e+01,1.2207031250000000e-03,0.000000e+00,1.381817e-01,2.819235e+00,5.767381e-01,2.134228e-01,2.982556e-01,1.971462e-01,2.255625e+01,9.468793e-01,5.545129e-01,2.500031e-02,0.000000e+00,2.297362e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.850070e+00,5.109101e+01,15,1.8525924324624585e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,431640625,1.2169741126195424e+01,729483825,431640625,2.2613334655761719e+01,4.8828125000000000e-04,0.000000e+00,1.514806e-01,-1.646700e+00,5.764102e-01,2.134279e-01,2.981825e-01,1.971999e-01,2.256547e+01,9.470590e-01,5.545129e-01,2.499915e-02,0.000000e+00,2.298302e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.983472e+00,6.816790e+01,15,1.8518357524500069e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,432373046,1.2169741327911616e+01,729483825,432373046,2.2608417510986328e+01,1.2207031250000000e-03,0.000000e+00,1.368421e-01,-1.648533e+00,4.517498e-01,2.642745e-01,2.986664e-01,2.328615e-01,2.250456e+01,9.162092e-01,5.013344e-01,2.320470e-02,0.000000e+00,2.294264e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.957914e+00,5.087887e+01,15,1.8568475577227543e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,432861328,1.2169741462390457e+01,729483825,432861328,2.2617813110351562e+01,7.3242187500000000e-04,0.000000e+00,1.438646e-01,9.302901e-02,4.513909e-01,2.643403e-01,2.985930e-01,2.329251e-01,2.251378e+01,9.163904e-01,5.013344e-01,2.320395e-02,0.000000e+00,2.295204e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.469901e+00,5.716714e+01,15,1.8560876782176496e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,433349609,1.2169741596869297e+01,729483825,433349609,2.2615514755249023e+01,9.7656250000000000e-04,0.000000e+00,1.427232e-01,-6.797946e-01,3.432241e-01,3.432240e-01,2.987939e-01,2.500000e-01,2.248856e+01,9.048809e-01,4.802845e-01,2.254278e-02,0.000000e+00,2.293570e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.550982e+00,5.833556e+01,15,1.8581687482201827e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,434082031,1.2169741798585488e+01,729483825,434082031,2.2627210617065430e+01,1.2207031250000000e-03,0.000000e+00,1.507133e-01,3.019726e+00,4.510319e-01,2.644063e-01,2.985197e-01,2.329887e-01,2.252300e+01,9.165717e-01,5.013344e-01,2.320321e-02,0.000000e+00,2.296144e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.037719e+00,5.997274e+01,15,1.8553273987759633e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,434082031,1.2169741798585488e+01,729483825,434082031,2.2622730255126953e+01,1.4648437500000000e-03,0.000000e+00,1.603859e-01,3.010950e+00,5.760826e-01,2.134330e-01,2.981094e-01,1.972536e-01,2.257469e+01,9.472387e-01,5.545129e-01,2.499798e-02,0.000000e+00,2.299241e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.482937e+00,7.250350e+01,15,1.8510792724058460e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,434326171,1.2169741877027684e+01,729483825,434326171,2.2624816894531250e+01,1.2207031250000000e-03,0.000000e+00,1.442362e-01,1.777194e+00,3.431397e-01,3.431397e-01,2.987204e-01,2.500000e-01,2.249778e+01,9.051035e-01,4.803632e-01,2.254463e-02,0.000000e+00,2.294506e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.448861e+00,5.461017e+01,15,1.8574076689053329e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,434814453,1.2169742011506525e+01,729483825,434814453,2.2634132385253906e+01,7.3242187500000000e-04,0.000000e+00,1.542796e-01,-2.757418e+00,3.430553e-01,3.430553e-01,2.986470e-01,2.500000e-01,2.250700e+01,9.053260e-01,4.804420e-01,2.254648e-02,0.000000e+00,2.295443e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.831939e+00,6.682641e+01,15,1.8566461896539017e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,436035156,1.2169742347701556e+01,729483825,436035156,2.2636608123779297e+01,1.9531250000000000e-03,0.000000e+00,1.544087e-01,6.417558e-01,4.506730e-01,2.644725e-01,2.984464e-01,2.330522e-01,2.253222e+01,9.167529e-01,5.013344e-01,2.320247e-02,0.000000e+00,2.297083e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.819616e+00,6.590849e+01,15,1.8545685191123125e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,436523437,1.2169742482180396e+01,729483825,436523437,2.2646009445190430e+01,7.3242187500000000e-04,0.000000e+00,1.554582e-01,2.465808e+00,4.503140e-01,2.645391e-01,2.983732e-01,2.331158e-01,2.254143e+01,9.169341e-01,5.013344e-01,2.320172e-02,0.000000e+00,2.298023e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.758282e+00,6.422519e+01,15,1.8538104393218251e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,436767578,1.2169742549417748e+01,729483825,436767578,2.2643444061279297e+01,1.7089843750000000e-03,0.000000e+00,1.521553e-01,1.138576e+00,3.429711e-01,3.429711e-01,2.985736e-01,2.500000e-01,2.251621e+01,9.055485e-01,4.805207e-01,2.254833e-02,0.000000e+00,2.296379e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.953412e+00,5.994631e+01,15,1.8558867100853784e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,437255859,1.2169742683896589e+01,729483825,437255859,2.2655410766601562e+01,4.8828125000000000e-04,0.000000e+00,1.790780e-01,-1.562755e+00,4.499550e-01,2.646058e-01,2.983000e-01,2.331793e-01,2.255065e+01,9.171152e-01,5.013344e-01,2.320098e-02,0.000000e+00,2.298963e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.601541e+00,8.142191e+01,15,1.8530521595630469e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,437500000,1.2169742751133938e+01,729483825,437500000,2.2652767181396484e+01,9.7656250000000000e-04,0.000000e+00,1.575303e-01,-2.994335e+00,3.428868e-01,3.428868e-01,2.985003e-01,2.500000e-01,2.252543e+01,9.057709e-01,4.805994e-01,2.255017e-02,0.000000e+00,2.297316e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.646149e+00,6.471764e+01,15,1.8551266306119829e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729483825,438232421,1.2169742964054976e+01,729483825,438232421,2.2662067413330078e+01,7.3242187500000000e-04,0.000000e+00,1.776910e-01,-8.249931e-01,3.428027e-01,3.428026e-01,2.984270e-01,2.500000e-01,2.253465e+01,9.059933e-01,4.806781e-01,2.255202e-02,0.000000e+00,2.298252e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.663596e+00,7.926227e+01,15,1.8543679509166231e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,463867187,1.4103363027866516e+01,729490767,463867187,1.4090797424316406e+01,9.7656250000000000e-04,0.000000e+00,2.044202e-01,-2.121863e+00,9.609296e-01,2.336819e-01,3.938625e-01,1.573487e-01,1.419080e+01,7.535188e-01,5.274274e-01,2.552254e-02,0.000000e+00,1.444241e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.568762e+00,7.777570e+01,15,2.3938519889304488e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,466064453,1.4103363644224075e+01,729490767,466064453,1.4099699974060059e+01,1.4648437500000000e-03,0.000000e+00,1.983663e-01,1.920657e+00,9.602141e-01,2.336648e-01,3.937176e-01,1.574131e-01,1.419950e+01,7.537233e-01,5.274274e-01,2.552011e-02,0.000000e+00,1.445132e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.797359e+00,7.847217e+01,15,2.3923837309999949e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,467773437,1.4103364114893807e+01,729490767,467773437,1.4121126174926758e+01,7.3242187500000000e-04,0.000000e+00,1.980171e-01,-1.294388e+00,8.205079e-01,2.655179e-01,3.942193e-01,1.847125e-01,1.416940e+01,7.261649e-01,4.787632e-01,2.350481e-02,0.000000e+00,1.444030e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.819404e+00,8.060974e+01,15,2.3974675253156597e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,469726562,1.4103364664014014e+01,729490767,469726562,1.4108615875244141e+01,3.4179687500000000e-03,0.000000e+00,1.810130e-01,1.720758e+00,9.594995e-01,2.336478e-01,3.935728e-01,1.574774e-01,1.420821e+01,7.539278e-01,5.274274e-01,2.551768e-02,0.000000e+00,1.446023e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.542254e+00,8.021593e+01,15,2.3909179114961305e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,470458984,1.4103364865730207e+01,729490767,470458984,1.4117516517639160e+01,2.4414062500000000e-03,0.000000e+00,1.572668e-01,-2.396986e+00,9.587858e-01,2.336308e-01,3.934282e-01,1.575418e-01,1.421692e+01,7.541322e-01,5.274274e-01,2.551526e-02,0.000000e+00,1.446914e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.829068e+00,5.751989e+01,15,2.3894532299246745e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,470703125,1.4103364932967557e+01,729490767,470703125,1.4126423835754395e+01,9.7656250000000000e-04,0.000000e+00,1.574122e-01,-1.070699e+00,9.580729e-01,2.336139e-01,3.932837e-01,1.576061e-01,1.422562e+01,7.543365e-01,5.274274e-01,2.551284e-02,0.000000e+00,1.447805e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.816984e+00,5.560355e+01,15,2.3879913119033533e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,471435546,1.4103365134683749e+01,729490767,471435546,1.4130031585693359e+01,2.1972656250000000e-03,0.000000e+00,1.789410e-01,-1.729939e+00,8.198432e-01,2.655156e-01,3.940740e-01,1.847882e-01,1.417811e+01,7.263693e-01,4.787632e-01,2.350298e-02,0.000000e+00,1.444921e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.650340e+00,8.058133e+01,15,2.3959950407791171e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,472167968,1.4103365347608923e+01,729490767,472167968,1.4135332107543945e+01,1.7089843750000000e-03,0.000000e+00,1.598738e-01,2.106819e+00,9.573609e-01,2.335970e-01,3.931393e-01,1.576704e-01,1.423433e+01,7.545409e-01,5.274274e-01,2.551042e-02,0.000000e+00,1.448695e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.662871e+00,5.421562e+01,15,2.3865308569379864e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,472412109,1.4103365414846275e+01,729490767,472412109,1.4138952255249023e+01,2.1972656250000000e-03,0.000000e+00,1.594673e-01,8.244662e-01,8.191791e-01,2.655133e-01,3.939289e-01,1.848638e-01,1.418681e+01,7.265735e-01,4.787632e-01,2.350116e-02,0.000000e+00,1.445813e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.703715e+00,5.901469e+01,15,2.3945241818603011e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,473144531,1.4103365616562465e+01,729490767,473144531,1.4144247055053711e+01,2.1972656250000000e-03,0.000000e+00,1.605919e-01,-1.742907e+00,9.566497e-01,2.335801e-01,3.929951e-01,1.577347e-01,1.424304e+01,7.547451e-01,5.274274e-01,2.550801e-02,0.000000e+00,1.449586e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.616725e+00,5.759530e+01,15,2.3850715399050273e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,473388671,1.4103365683799817e+01,729490767,473388671,1.4147856712341309e+01,1.4648437500000000e-03,0.000000e+00,1.544850e-01,-2.980242e+00,8.185159e-01,2.655111e-01,3.937838e-01,1.849395e-01,1.419552e+01,7.267777e-01,4.787632e-01,2.349933e-02,0.000000e+00,1.446704e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.001359e+01,5.116745e+01,15,2.3930551111209839e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,473632812,1.4103365751041306e+01,729490767,473632812,1.4153154373168945e+01,1.7089843750000000e-03,0.000000e+00,1.628165e-01,-8.038309e-02,9.559394e-01,2.335633e-01,3.928510e-01,1.577989e-01,1.425175e+01,7.549493e-01,5.274274e-01,2.550560e-02,0.000000e+00,1.450477e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.482430e+00,5.971008e+01,15,2.3836149864222032e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,474853515,1.4103366087232200e+01,729490767,474853515,1.4156771659851074e+01,1.9531250000000000e-03,0.000000e+00,1.522657e-01,2.316849e-01,8.178534e-01,2.655090e-01,3.936389e-01,1.850151e-01,1.420423e+01,7.269819e-01,4.787632e-01,2.349751e-02,0.000000e+00,1.447595e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.015643e+01,4.710295e+01,15,2.3915876659993933e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,475341796,1.4103366232920024e+01,729490767,475341796,1.4160455703735352e+01,1.9531250000000000e-03,0.000000e+00,1.643671e-01,-3.316701e-01,6.554899e-01,3.211247e-01,3.944565e-01,2.206954e-01,1.415520e+01,7.004517e-01,4.300989e-01,2.163965e-02,0.000000e+00,1.444719e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.424955e+00,6.685255e+01,15,2.3998726267418182e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,475830078,1.4103366367394726e+01,729490767,475830078,1.4165689468383789e+01,2.1972656250000000e-03,0.000000e+00,1.545736e-01,2.671373e+00,8.171916e-01,2.655069e-01,3.934942e-01,1.850907e-01,1.421294e+01,7.271861e-01,4.787632e-01,2.349569e-02,0.000000e+00,1.448486e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.000172e+01,5.079615e+01,15,2.3901220090573014e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,476562500,1.4103366569110916e+01,729490767,476562500,1.4169372558593750e+01,1.9531250000000000e-03,0.000000e+00,1.465522e-01,2.543987e+00,6.548285e-01,3.211854e-01,3.943110e-01,2.207859e-01,1.416391e+01,7.006572e-01,4.300989e-01,2.163845e-02,0.000000e+00,1.445610e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.056740e+01,4.483340e+01,15,2.3983960781609599e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,477050781,1.4103366703589757e+01,729490767,477050781,1.4174508094787598e+01,1.7089843750000000e-03,0.000000e+00,1.676892e-01,-1.410197e+00,4.535208e-01,4.535208e-01,3.948128e-01,2.500000e-01,1.413391e+01,6.848130e-01,3.988586e-01,2.054318e-02,0.000000e+00,1.444041e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.245188e+00,7.065401e+01,15,2.4034862123857574e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,477539062,1.4103366838068597e+01,729490767,477539062,1.4178286552429199e+01,1.7089843750000000e-03,0.000000e+00,1.421240e-01,-1.211849e+00,6.541677e-01,3.212465e-01,3.941655e-01,2.208764e-01,1.417262e+01,7.008628e-01,4.300989e-01,2.163725e-02,0.000000e+00,1.446502e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.089330e+01,3.576317e+01,15,2.3969227808155544e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,478271484,1.4103367039784789e+01,729490767,478271484,1.4183307647705078e+01,1.9531250000000000e-03,0.000000e+00,1.439553e-01,1.419897e+00,4.533532e-01,4.533532e-01,3.946669e-01,2.500000e-01,1.414263e+01,6.850662e-01,3.989569e-01,2.054571e-02,0.000000e+00,1.444928e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.076612e+01,4.151365e+01,15,2.4020055997605834e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,478271484,1.4103367039784789e+01,729490767,478271484,1.4187199592590332e+01,1.7089843750000000e-03,0.000000e+00,1.471632e-01,8.761101e-01,6.535072e-01,3.213078e-01,3.940203e-01,2.209669e-01,1.418133e+01,7.010682e-01,4.300989e-01,2.163605e-02,0.000000e+00,1.447393e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.051706e+01,4.231488e+01,15,2.3954501337172394e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,479736328,1.4103367454422017e+01,729490767,479736328,1.4192112922668457e+01,2.1972656250000000e-03,0.000000e+00,1.362237e-01,-1.571772e+00,4.531857e-01,4.531857e-01,3.945211e-01,2.500000e-01,1.415134e+01,6.853193e-01,3.990552e-01,2.054824e-02,0.000000e+00,1.445815e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.137367e+01,3.439804e+01,15,2.4005267753149080e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729490767,479980468,1.4103367521663507e+01,729490767,479980468,1.4200911521911621e+01,1.4648437500000000e-03,0.000000e+00,1.379724e-01,-2.611505e-01,4.530185e-01,4.530184e-01,3.943755e-01,2.500000e-01,1.416005e+01,6.855723e-01,3.991534e-01,2.055077e-02,0.000000e+00,1.446702e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.122607e+01,3.647243e+01,15,2.3990505518575946e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,953857421,1.1287451997453140e+01,729566821,953857421,1.0159644126892090e+01,1.7089843750000000e-03,0.000000e+00,1.824229e-01,-1.110251e+00,1.051673e+00,3.085168e-01,4.786034e-01,1.753721e-01,1.025545e+01,6.049087e-01,4.339938e-01,2.260905e-02,0.000000e+00,1.044898e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.713128e+00,1.101276e+02,15,3.1396191714556960e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,955566406,1.1287452468127013e+01,729566821,955566406,1.0169228553771973e+01,1.9531250000000000e-03,0.000000e+00,1.698733e-01,2.513761e+00,1.050451e+00,3.085010e-01,4.783421e-01,1.754786e-01,1.026479e+01,6.051580e-01,4.339938e-01,2.260624e-02,0.000000e+00,1.045856e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.042595e+01,8.878841e+01,15,3.1367622214620154e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,957519531,1.1287453017243081e+01,729566821,957519531,1.0178808212280273e+01,2.9296875000000000e-03,0.000000e+00,1.448258e-01,5.180047e-01,1.049232e+00,3.084853e-01,4.780812e-01,1.755850e-01,1.027413e+01,6.054072e-01,4.339938e-01,2.260345e-02,0.000000e+00,1.046815e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.222356e+01,5.650437e+01,15,3.1339114346653871e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,957763671,1.1287453084480431e+01,729566821,957763671,1.0188406944274902e+01,1.7089843750000000e-03,0.000000e+00,1.410623e-01,1.855089e+00,1.048014e+00,3.084697e-01,4.778207e-01,1.756914e-01,1.028347e+01,6.056564e-01,4.339938e-01,2.260065e-02,0.000000e+00,1.047773e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.254397e+01,4.342907e+01,15,3.1310640376271381e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,958007812,1.1287453151721921e+01,729566821,958007812,1.0197989463806152e+01,9.7656250000000000e-04,0.000000e+00,1.599976e-01,3.077241e+00,1.046799e+00,3.084543e-01,4.775605e-01,1.757977e-01,1.029281e+01,6.059054e-01,4.339938e-01,2.259787e-02,0.000000e+00,1.048732e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.105441e+01,7.072723e+01,15,3.1282237282654992e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,958740234,1.1287453353438112e+01,729566821,958740234,1.0189829826354980e+01,2.9296875000000000e-03,0.000000e+00,1.551787e-01,1.945167e+00,8.317288e-01,3.758519e-01,4.793093e-01,2.143711e-01,1.023029e+01,5.795941e-01,3.843558e-01,2.054021e-02,0.000000e+00,1.044607e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.143246e+01,7.153362e+01,15,3.1473401165631993e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,958984375,1.1287453420675464e+01,729566821,958984375,1.0199428558349609e+01,1.4648437500000000e-03,0.000000e+00,1.455263e-01,-2.999292e+00,8.305528e-01,3.759263e-01,4.790469e-01,2.145015e-01,1.023963e+01,5.798447e-01,3.843558e-01,2.053840e-02,0.000000e+00,1.045566e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.218519e+01,5.206169e+01,15,3.1444686830564454e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729566821,959228515,1.1287453487912813e+01,729566821,959228515,1.0207566261291504e+01,1.7089843750000000e-03,0.000000e+00,1.680216e-01,-2.100350e-01,1.045586e+00,3.084390e-01,4.773007e-01,1.759040e-01,1.030215e+01,6.061544e-01,4.339938e-01,2.259509e-02,0.000000e+00,1.049690e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.052172e+01,7.831284e+01,15,3.1253883494615025e+00,0.000000e+00,