<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE LIGO_LW [
<!ELEMENT LIGO_LW ((LIGO_LW|Comment|Param|Table|Array|Stream|IGWDFrame|AdcData|AdcInterval|Time|Detector)*)>
<!ATTLIST LIGO_LW
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Comment (#PCDATA)>

<!ELEMENT Param (#PCDATA|Comment)*>
<!ATTLIST Param 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED
         Unit CDATA #IMPLIED
         DataUnit CDATA #IMPLIED>

<!ELEMENT Table (Comment?,Column*,Stream?)>
<!ATTLIST Table 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Column EMPTY>
<!ATTLIST Column
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Array (Dim*,Stream?)>
<!ATTLIST Array 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Dim (#PCDATA)>
<!ATTLIST Dim 
         Name  CDATA #IMPLIED
         Unit CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED>

<!ELEMENT Stream (#PCDATA)>
<!ATTLIST Stream 
         Name      CDATA #IMPLIED
         Type      (Remote|Local) "Local"
         Delimiter CDATA ","
         Encoding  CDATA #IMPLIED
         Content   CDATA #IMPLIED>

<!ELEMENT IGWDFrame ((Comment|Param|Time|Detector|AdcData|LIGO_LW|Stream?|Array|IGWDFrame)*)>
<!ATTLIST IGWDFrame 
         Name CDATA #IMPLIED>

<!ELEMENT Detector ((Comment|Param|LIGO_LW)*)>
<!ATTLIST Detector 
         Name CDATA #IMPLIED>

<!ELEMENT AdcData ((AdcData|Comment|Param|Time|LIGO_LW|Array)*)>
<!ATTLIST AdcData 
         Name CDATA #IMPLIED>

<!ELEMENT AdcInterval ((AdcData|Comment|Time)*)>
<!ATTLIST AdcInterval 
         Name CDATA #IMPLIED
         StartTime CDATA #IMPLIED
         DeltaT CDATA #IMPLIED>

<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time 
         Name CDATA #IMPLIED
         Type (GPS|Unix|ISO-8601) "ISO-8601">
]>

<LIGO_LW>
   <Comment>metadata</Comment>
   <Table Name="processgroup:process:table">
      <Column Name="processgroup:process:program" Type="lstring"/>
      <Column Name="processgroup:process:version" Type="lstring"/>
      <Column Name="processgroup:process:cvs_repository" Type="lstring"/>
      <Column Name="processgroup:process:cvs_entry_time" Type="int_4s"/>
      <Column Name="processgroup:process:comment" Type="lstring"/>
      <Column Name="processgroup:process:is_online" Type="int_4s"/>
      <Column Name="processgroup:process:node" Type="lstring"/>
      <Column Name="processgroup:process:username" Type="lstring"/>
      <Column Name="processgroup:process:unix_procid" Type="int_4s"/>
      <Column Name="processgroup:process:start_time" Type="int_4s"/>
      <Column Name="processgroup:process:end_time" Type="int_4s"/>
      <Column Name="processgroup:process:jobid" Type="int_4s"/>
      <Column Name="processgroup:process:domain" Type="lstring"/>
      <Column Name="processgroup:process:ifos" Type="lstring"/>
      <Column Name="processgroup:process:process_id" Type="ilwd:char"/>
      <Stream Name="processgroup:process:table" Type="Local" Delimiter=",">
         "sire","1.15","/usr/local/cvs/lscsoft/lalapps/src/inspiral/sire.c\,v",769623277," ",0,"ldas-grid","dbrown",25134,776378895,776378895,0,"lalapps","","process:process_id:0"
      </Stream>
   </Table>
   <Table Name="process_paramsgroup:process_params:table">
      <Column Name="process_paramsgroup:process_params:program" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:process_id" Type="ilwd:char"/>
      <Column Name="process_paramsgroup:process_params:param" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:type" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:value" Type="lstring"/>
      <Stream Name="process_paramsgroup:process_params:table" Type="Local" Delimiter=",">
         "sire","process:process_id:0","--playground-only","string"," ",
         "sire","process:process_id:0","--input","string","l1-inca_l1h1.files",
         "sire","process:process_id:0","--output","string","l1-inca_l1h1.xml",
         "sire","process:process_id:0","--summary-file","string","l1-inca_l1h1.txt",
         "sire","process:process_id:0","--debug-level","string","33"
      </Stream>
   </Table>
   <Table Name="sngl_inspiralgroup:sngl_inspiral:table">
      <Column Name="sngl_inspiralgroup:sngl_inspiral:process_id" Type="ilwd:char"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ifo" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:search" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:channel" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_gmst" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:template_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:event_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:amplitude" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eff_distance" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:coa_phase" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass1" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mchirp" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eta" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau4" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau5" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ttotal" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:f_final" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:snr" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq_dof" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:sigmasq" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:alpha" Type="real_4"/>
      <Stream Name="sngl_inspiralgroup:sngl_inspiral:table" Type="Local" Delimiter=",">
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,873779296,1.0455689096359743e+01,729649999,873779296,8.9296970367431641e+00,9.7656250000000000e-04,0.000000e+00,3.323758e-01,2.619315e+00,1.038170e+00,3.588442e-01,5.172071e-01,1.908854e-01,9.011706e+00,5.496685e-01,3.916852e-01,2.113103e-02,0.000000e+00,9.190821e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.884382e+01,2.296438e+02,15,3.9228019432817014e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,875488281,1.0455689567029475e+01,729649999,875488281,8.9391393661499023e+00,1.9531250000000000e-03,0.000000e+00,2.830227e-01,-1.446903e-01,1.036741e+00,3.588512e-01,5.168912e-01,1.910150e-01,9.020888e+00,5.499267e-01,3.916852e-01,2.112845e-02,0.000000e+00,9.200258e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.211850e+01,9.952728e+01,15,3.9188092438931115e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,876953125,1.0455689981670844e+01,729649999,876953125,8.9485683441162109e+00,1.7089843750000000e-03,0.000000e+00,2.698635e-01,3.133023e+00,1.035315e+00,3.588585e-01,5.165758e-01,1.911446e-01,9.030069e+00,5.501848e-01,3.916852e-01,2.112587e-02,0.000000e+00,9.209695e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.318527e+01,4.706089e+01,15,3.9148253412322646e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,878662109,1.0455690452340576e+01,729649999,878662109,8.9580106735229492e+00,1.4648437500000000e-03,0.000000e+00,2.823077e-01,4.069207e-01,1.033891e+00,3.588660e-01,5.162609e-01,1.912742e-01,9.039250e+00,5.504429e-01,3.916852e-01,2.112329e-02,0.000000e+00,9.219131e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.215198e+01,9.796970e+01,15,3.9108471902780195e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,878906250,1.0455690519577928e+01,729649999,878906250,8.9665660858154297e+00,9.7656250000000000e-04,0.000000e+00,3.259172e-01,3.035258e+00,5.953484e-01,5.953484e-01,5.182809e-01,2.500000e-01,8.980611e+00,5.216725e-01,3.326873e-01,1.876188e-02,0.000000e+00,9.188357e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.925048e+01,2.088099e+02,15,3.9363857825963798e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,878906250,1.0455690519577928e+01,729649999,878906250,8.9667615890502930e+00,1.4648437500000000e-03,0.000000e+00,3.018758e-01,1.375364e+00,7.176690e-01,4.966666e-01,5.179952e-01,2.417195e-01,8.988866e+00,5.248845e-01,3.396041e-01,1.901923e-02,0.000000e+00,9.193166e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.077404e+01,1.503880e+02,15,3.9327696508223561e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,879882812,1.0455690788535609e+01,729649999,879882812,8.9674491882324219e+00,7.3242187500000000e-04,0.000000e+00,3.254634e-01,-2.992814e+00,1.032470e+00,3.588738e-01,5.159466e-01,1.914037e-01,9.048432e+00,5.507008e-01,3.916852e-01,2.112072e-02,0.000000e+00,9.228568e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.920493e+01,2.119299e+02,15,3.9068798660656128e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,880615234,1.0455691001456644e+01,729649999,880615234,8.9758443832397461e+00,1.9531250000000000e-03,0.000000e+00,2.803356e-01,1.922345e-01,5.949835e-01,5.949835e-01,5.179632e-01,2.500000e-01,8.989792e+00,5.219925e-01,3.328234e-01,1.876572e-02,0.000000e+00,9.197727e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.236911e+01,9.391687e+01,15,3.9323653396818287e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,880859375,1.0455691068698135e+01,729649999,880859375,8.9762039184570312e+00,1.9531250000000000e-03,0.000000e+00,2.674004e-01,-1.066211e+00,7.158342e-01,4.972623e-01,5.176780e-01,2.418841e-01,8.998048e+00,5.251457e-01,3.396041e-01,1.901787e-02,0.000000e+00,9.202607e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.344043e+01,5.218000e+01,15,3.9287566512928187e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,882080078,1.0455691404889027e+01,729649999,882080078,8.9851236343383789e+00,1.7089843750000000e-03,0.000000e+00,2.623543e-01,-2.851465e+00,5.946192e-01,5.946192e-01,5.176461e-01,2.500000e-01,8.998973e+00,5.223123e-01,3.329593e-01,1.876955e-02,0.000000e+00,9.207096e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.389005e+01,3.786505e+01,15,3.9283533551593386e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,882080078,1.0455691404889027e+01,729649999,882080078,8.9856472015380859e+00,1.2207031250000000e-03,0.000000e+00,2.690781e-01,1.941134e+00,7.139923e-01,4.978676e-01,5.173613e-01,2.420486e-01,9.007229e+00,5.254069e-01,3.396041e-01,1.901652e-02,0.000000e+00,9.212049e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.328240e+01,6.290179e+01,15,3.9247524484910251e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,883544921,1.0455691808325549e+01,729649999,883544921,8.9944019317626953e+00,1.2207031250000000e-03,0.000000e+00,2.893857e-01,3.764789e-01,5.942555e-01,5.942554e-01,5.173295e-01,2.500000e-01,9.008155e+00,5.226320e-01,3.330951e-01,1.877338e-02,0.000000e+00,9.216465e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.164745e+01,1.180889e+02,15,3.9243484756861797e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,883789062,1.0455691886767745e+01,729649999,883789062,8.9950857162475586e+00,9.7656250000000000e-04,0.000000e+00,3.133928e-01,-7.978837e-01,7.121429e-01,4.984829e-01,5.170452e-01,2.422131e-01,9.016411e+00,5.256680e-01,3.396041e-01,1.901517e-02,0.000000e+00,9.221490e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.998002e+01,1.778389e+02,15,3.9207550124028799e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729649999,885986328,1.0455692491916318e+01,729649999,885986328,9.0036792755126953e+00,9.7656250000000000e-04,0.000000e+00,3.430896e-01,-1.619751e+00,5.938924e-01,5.938923e-01,5.170133e-01,2.500000e-01,9.017337e+00,5.229515e-01,3.332309e-01,1.877720e-02,0.000000e+00,9.225835e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.824967e+01,2.231106e+02,15,3.9203527312764471e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,310058593,1.7511464492008091e+01,729675331,310058593,2.0436677932739258e+01,2.4414062500000000e-04,0.000000e+00,9.584991e-02,1.125944e+00,6.814203e-01,2.072830e-01,3.163995e-01,1.788402e-01,2.044191e+01,9.110934e-01,5.652069e-01,2.569975e-02,0.000000e+00,2.081349e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.697004e+01,1.184969e+03,15,2.0268665383226484e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,310791015,1.7511464693724282e+01,729675331,310791015,2.0446277618408203e+01,7.3242187500000000e-04,0.000000e+00,9.074973e-02,-3.020743e+00,6.810157e-01,2.072790e-01,3.163123e-01,1.788950e-01,2.045131e+01,9.112839e-01,5.652069e-01,2.569818e-02,0.000000e+00,2.082308e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.959837e+01,9.830160e+02,15,2.0259342646149776e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,311767578,1.7511464962681963e+01,729675331,311767578,2.0455875396728516e+01,9.7656250000000000e-04,0.000000e+00,8.400438e-02,-5.133662e-01,6.806115e-01,2.072750e-01,3.162251e-01,1.789498e-01,2.046071e+01,9.114744e-01,5.652069e-01,2.569661e-02,0.000000e+00,2.083267e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.356868e+01,6.125255e+02,15,2.0250031805377294e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,312988281,1.7511465310081839e+01,729675331,312988281,2.0465457916259766e+01,1.2207031250000000e-03,0.000000e+00,7.991312e-02,2.396137e+00,6.802076e-01,2.072711e-01,3.161379e-01,1.790047e-01,2.047011e+01,9.116648e-01,5.652069e-01,2.569505e-02,0.000000e+00,2.084227e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.629826e+01,3.262712e+02,15,2.0240732860909034e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,313232421,1.7511465377319190e+01,729675331,313232421,2.0463169097900391e+01,7.3242187500000000e-04,0.000000e+00,9.411731e-02,3.542098e-01,5.776692e-01,2.378758e-01,3.166125e-01,2.066015e-01,2.041900e+01,8.836882e-01,5.180976e-01,2.398073e-02,0.000000e+00,2.080857e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.786153e+01,1.003594e+03,15,2.0291405168750249e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,313964843,1.7511465579035381e+01,729675331,313964843,2.0472755432128906e+01,7.3242187500000000e-04,0.000000e+00,9.085688e-02,2.506525e+00,5.772792e-01,2.378904e-01,3.165250e-01,2.066650e-01,2.042840e+01,8.838792e-01,5.180976e-01,2.397958e-02,0.000000e+00,2.081816e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.956764e+01,8.951370e+02,15,2.0282064587217207e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,314697265,1.7511465780751571e+01,729675331,314697265,2.0475053787231445e+01,1.4648437500000000e-03,0.000000e+00,8.189656e-02,-3.264523e-01,6.798041e-01,2.072672e-01,3.160508e-01,1.790595e-01,2.047952e+01,9.118552e-01,5.652069e-01,2.569349e-02,0.000000e+00,2.085186e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.492218e+01,4.625393e+02,15,2.0231437881875518e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,314941406,1.7511465847993062e+01,729675331,314941406,2.0482364654541016e+01,9.7656250000000000e-04,0.000000e+00,8.781897e-02,-1.276409e+00,5.768893e-01,2.379051e-01,3.164376e-01,2.067284e-01,2.043781e+01,8.840703e-01,5.180976e-01,2.397843e-02,0.000000e+00,2.082776e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.127053e+01,7.622195e+02,15,2.0272725988401536e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,315429687,1.7511465982467765e+01,729675331,315429687,2.0480125427246094e+01,2.4414062500000000e-04,0.000000e+00,1.011991e-01,-2.419730e+00,4.381123e-01,3.045161e-01,3.169298e-01,2.419093e-01,2.038493e+01,8.577660e-01,4.709883e-01,2.239627e-02,0.000000e+00,2.079411e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.454942e+01,1.207510e+03,15,2.0325307653070663e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,316406250,1.7511466262630289e+01,729675331,316406250,2.0489713668823242e+01,7.3242187500000000e-04,0.000000e+00,9.462888e-02,6.615698e-02,4.376025e-01,3.046834e-01,3.168421e-01,2.419837e-01,2.039434e+01,8.579589e-01,4.709883e-01,2.239555e-02,0.000000e+00,2.080371e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.763155e+01,9.506119e+02,15,2.0315933365342321e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,316406250,1.7511466262630289e+01,729675331,316406250,2.0491945266723633e+01,1.2207031250000000e-03,0.000000e+00,8.425167e-02,1.918417e+00,5.764998e-01,2.379199e-01,3.163503e-01,2.067918e-01,2.044721e+01,8.842614e-01,5.180976e-01,2.397728e-02,0.000000e+00,2.083735e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.342908e+01,5.643599e+02,15,2.0263405234042200e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,316650390,1.7511466329871780e+01,729675331,316650390,2.0490816116333008e+01,4.8828125000000000e-04,0.000000e+00,9.740450e-02,2.758643e+00,3.640534e-01,3.640533e-01,3.169269e-01,2.500000e-01,2.038525e+01,8.531082e-01,4.617856e-01,2.210439e-02,0.000000e+00,2.079868e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.628456e+01,1.048864e+03,15,2.0324990418291364e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,316894531,1.7511466397109132e+01,729675331,316894531,2.0484634399414062e+01,1.4648437500000000e-03,0.000000e+00,8.968587e-02,-2.495982e+00,6.794009e-01,2.072633e-01,3.159638e-01,1.791143e-01,2.048892e+01,9.120456e-01,5.652069e-01,2.569192e-02,0.000000e+00,2.086145e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.014062e+01,9.219927e+02,15,2.0222154799146224e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,317626953,1.7511466598825322e+01,729675331,317626953,2.0500324249267578e+01,7.3242187500000000e-04,0.000000e+00,9.283987e-02,-1.052245e+00,3.639526e-01,3.639526e-01,3.168391e-01,2.500000e-01,2.039466e+01,8.533444e-01,4.618708e-01,2.210643e-02,0.000000e+00,2.080824e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.854902e+01,8.738311e+02,15,2.0315616130563019e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,317626953,1.7511466598825322e+01,729675331,317626953,2.0499320983886719e+01,9.7656250000000000e-04,0.000000e+00,9.182072e-02,2.913114e+00,4.370917e-01,3.048519e-01,3.167545e-01,2.420581e-01,2.040375e+01,8.581519e-01,4.709883e-01,2.239483e-02,0.000000e+00,2.081330e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.907695e+01,8.451987e+02,15,2.0306565025766091e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,318115234,1.7511466733304164e+01,729675331,318115234,2.0501541137695312e+01,1.4648437500000000e-03,0.000000e+00,8.434628e-02,-8.428134e-01,5.761106e-01,2.379347e-01,3.162630e-01,2.068552e-01,2.045662e+01,8.844524e-01,5.180976e-01,2.397613e-02,0.000000e+00,2.084694e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.335689e+01,5.750688e+02,15,2.0254092410552346e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,318603515,1.7511466867778864e+01,729675331,318603515,2.0508907318115234e+01,9.7656250000000000e-04,0.000000e+00,9.115382e-02,-8.740125e-01,4.365801e-01,3.050217e-01,3.166669e-01,2.421325e-01,2.041315e+01,8.583447e-01,4.709883e-01,2.239412e-02,0.000000e+00,2.082290e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.942462e+01,8.570680e+02,15,2.0297212547928826e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,318847656,1.7511466935020355e+01,729675331,318847656,2.0509828567504883e+01,9.7656250000000000e-04,0.000000e+00,9.188510e-02,1.756916e+00,3.638519e-01,3.638519e-01,3.167515e-01,2.500000e-01,2.040407e+01,8.535805e-01,4.619560e-01,2.210846e-02,0.000000e+00,2.081780e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.904218e+01,8.591249e+02,15,2.0306251756421531e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,319824218,1.7511467215182879e+01,729675331,319824218,2.0518514633178711e+01,9.7656250000000000e-04,0.000000e+00,8.908550e-02,1.963652e+00,4.360675e-01,3.051927e-01,3.165793e-01,2.422069e-01,2.042256e+01,8.585376e-01,4.709883e-01,2.239340e-02,0.000000e+00,2.083250e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.056046e+01,7.892364e+02,15,2.0287858087374190e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,320068359,1.7511467282420231e+01,729675331,320068359,2.0519325256347656e+01,1.2207031250000000e-03,0.000000e+00,9.082736e-02,-1.734542e+00,3.637513e-01,3.637513e-01,3.166639e-01,2.500000e-01,2.041347e+01,8.538166e-01,4.620412e-01,2.211050e-02,0.000000e+00,2.082736e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.960187e+01,8.494164e+02,15,2.0296891347714784e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,320312500,1.7511467349657583e+01,729675331,320312500,2.0511140823364258e+01,1.4648437500000000e-03,0.000000e+00,8.885828e-02,-3.022706e+00,5.757216e-01,2.379496e-01,3.161758e-01,2.069186e-01,2.046602e+01,8.846434e-01,5.180976e-01,2.397498e-02,0.000000e+00,2.085654e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.063591e+01,8.386613e+02,15,2.0244783552497235e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,321289062,1.7511467618615264e+01,729675331,321289062,2.0528831481933594e+01,9.7656250000000000e-04,0.000000e+00,8.933159e-02,1.086282e+00,3.636508e-01,3.636508e-01,3.165764e-01,2.500000e-01,2.042288e+01,8.540527e-01,4.621263e-01,2.211254e-02,0.000000e+00,2.083692e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.042080e+01,8.134629e+02,15,2.0287546800746998e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,321533203,1.7511467685852615e+01,729675331,321533203,2.0528097152709961e+01,1.2207031250000000e-03,0.000000e+00,8.818151e-02,-8.221334e-01,4.355539e-01,3.053651e-01,3.164919e-01,2.422813e-01,2.043197e+01,8.587304e-01,4.709883e-01,2.239268e-02,0.000000e+00,2.084210e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.106703e+01,7.625592e+02,15,2.0278523453993259e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,323242187,1.7511468167731330e+01,729675331,323242187,2.0538335800170898e+01,1.2207031250000000e-03,0.000000e+00,8.906166e-02,-1.425995e+00,3.635503e-01,3.635503e-01,3.164889e-01,2.500000e-01,2.043229e+01,8.542887e-01,4.622115e-01,2.211458e-02,0.000000e+00,2.084648e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.056196e+01,8.052183e+02,15,2.0278202253779217e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,323486328,1.7511468234968682e+01,729675331,323486328,2.0537702560424805e+01,1.2207031250000000e-03,0.000000e+00,8.974199e-02,2.983200e+00,4.350393e-01,3.055387e-01,3.164045e-01,2.423556e-01,2.044137e+01,8.589232e-01,4.709883e-01,2.239197e-02,0.000000e+00,2.085170e+01,0.000000e+00,0.000000e+00,0.000000e+00,5.016750e+01,8.546788e+02,15,2.0269190803329700e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729675331,325683593,1.7511468840117256e+01,729675331,325683593,2.0547845840454102e+01,1.4648437500000000e-03,0.000000e+00,9.189977e-02,2.911138e+00,3.634499e-01,3.634499e-01,3.164015e-01,2.500000e-01,2.044169e+01,8.545247e-01,4.622966e-01,2.211661e-02,0.000000e+00,2.085604e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.898920e+01,9.561636e+02,15,2.0268869603115657e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729789943,225341796,1.4352734720499980e+00,729789943,225341796,5.5156035423278809e+00,1.7089843750000000e-03,0.000000e+00,8.800600e-02,-1.641542e+00,7.933726e-01,7.933725e-01,6.906709e-01,2.500000e-01,5.564966e+00,3.914641e-01,2.747255e-01,1.704935e-02,0.000000e+00,5.698754e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.910041e+01,2.193013e+03,15,3.6981611955343524e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729789943,226806640,1.4352738754865195e+00,729789943,226806640,5.5243620872497559e+00,1.9531250000000000e-03,0.000000e+00,7.479016e-02,1.437844e+00,7.926317e-01,7.926317e-01,6.900260e-01,2.500000e-01,5.573638e+00,3.918301e-01,2.748967e-01,1.705466e-02,0.000000e+00,5.707626e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.124756e+01,6.520609e+02,15,3.6924077989648552e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729789943,228027343,1.4352742228863968e+00,729789943,228027343,5.5331220626831055e+00,1.4648437500000000e-03,0.000000e+00,7.208605e-02,-1.975348e+00,7.918926e-01,7.918926e-01,6.893826e-01,2.500000e-01,5.582310e+00,3.921957e-01,2.750677e-01,1.705996e-02,0.000000e+00,5.716498e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.422983e+01,1.225388e+02,15,3.6866705536626881e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729789943,229492187,1.4352746263187792e+00,729789943,229492187,5.5418772697448730e+00,1.2207031250000000e-03,0.000000e+00,7.917909e-02,1.156885e+00,7.911555e-01,7.911554e-01,6.887408e-01,2.500000e-01,5.590983e+00,3.925612e-01,2.752385e-01,1.706526e-02,0.000000e+00,5.725370e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.662485e+01,1.142678e+03,15,3.6809530050279960e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729789943,231445312,1.4352751754348476e+00,729789943,231445312,5.5506381988525391e+00,4.8828125000000000e-04,0.000000e+00,9.200618e-02,-1.500971e+00,7.904201e-01,7.904200e-01,6.881006e-01,2.500000e-01,5.599655e+00,3.929264e-01,2.754092e-01,1.707055e-02,0.000000e+00,5.734243e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.589108e+01,2.470364e+03,15,3.6752523955273318e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729802794,493408203,5.0148439331766630e+00,729802794,493408203,2.3139602661132812e+01,1.4648437500000000e-03,0.000000e+00,1.121485e-01,1.199985e+00,6.204269e-01,1.956964e-01,2.939090e-01,1.822896e-01,2.311495e+01,9.767615e-01,5.869188e-01,2.609067e-02,0.000000e+00,2.353089e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.793527e+01,4.255351e+02,15,9.8150486988448584e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729802794,495605468,5.0148445495342218e+00,729802794,495605468,2.3148530960083008e+01,2.1972656250000000e-03,0.000000e+00,9.819195e-02,-1.124915e+00,6.201196e-01,1.956945e-01,2.938422e-01,1.823357e-01,2.312371e+01,9.769306e-01,5.869188e-01,2.608939e-02,0.000000e+00,2.353982e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.189981e+01,2.091943e+02,15,9.8113302625635281e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729802794,497558593,5.0148450874413051e+00,729802794,497558593,2.3157474517822266e+01,2.1972656250000000e-03,0.000000e+00,9.216824e-02,2.623427e+00,6.198124e-01,1.956926e-01,2.937754e-01,1.823817e-01,2.313248e+01,9.770995e-01,5.869188e-01,2.608811e-02,0.000000e+00,2.354875e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.397820e+01,8.305280e+01,15,9.8076139976318526e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729802794,497802734,5.0148451546827948e+00,729802794,497802734,2.3172378540039062e+01,9.7656250000000000e-04,0.000000e+00,1.116543e-01,-2.812454e+00,5.200831e-01,2.268529e-01,2.940584e-01,2.114707e-01,2.309539e+01,9.471834e-01,5.367078e-01,2.432080e-02,0.000000e+00,2.353019e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.807079e+01,4.243676e+02,15,9.8233617109926374e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729802794,499023437,5.0148455020826725e+00,729802794,499023437,2.3166399002075195e+01,1.4648437500000000e-03,0.000000e+00,9.464224e-02,-4.678411e-01,6.195055e-01,1.956906e-01,2.937087e-01,1.824278e-01,2.314124e+01,9.772685e-01,5.869188e-01,2.608684e-02,0.000000e+00,2.355768e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.308372e+01,1.548541e+02,15,9.8038966470253488e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729802794,500000000,5.0148457710362146e+00,729802794,500000000,2.3175319671630859e+01,7.3242187500000000e-04,0.000000e+00,1.090282e-01,2.037939e+00,6.191989e-01,1.956888e-01,2.936420e-01,1.824738e-01,2.315000e+01,9.774375e-01,5.869188e-01,2.608557e-02,0.000000e+00,2.356661e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.871299e+01,3.997694e+02,15,9.8001901531671134e+00,0.000000e+00,