<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE LIGO_LW [
<!ELEMENT LIGO_LW ((LIGO_LW|Comment|Param|Table|Array|Stream|IGWDFrame|AdcData|AdcInterval|Time|Detector)*)>
<!ATTLIST LIGO_LW
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Comment (#PCDATA)>

<!ELEMENT Param (#PCDATA|Comment)*>
<!ATTLIST Param 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED
         Unit CDATA #IMPLIED
         DataUnit CDATA #IMPLIED>

<!ELEMENT Table (Comment?,Column*,Stream?)>
<!ATTLIST Table 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Column EMPTY>
<!ATTLIST Column
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Array (Dim*,Stream?)>
<!ATTLIST Array 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Dim (#PCDATA)>
<!ATTLIST Dim 
         Name  CDATA #IMPLIED
         Unit CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED>

<!ELEMENT Stream (#PCDATA)>
<!ATTLIST Stream 
         Name      CDATA #IMPLIED
         Type      (Remote|Local) "Local"
         Delimiter CDATA ","
         Encoding  CDATA #IMPLIED
         Content   CDATA #IMPLIED>

<!ELEMENT IGWDFrame ((Comment|Param|Time|Detector|AdcData|LIGO_LW|Stream?|Array|IGWDFrame)*)>
<!ATTLIST IGWDFrame 
         Name CDATA #IMPLIED>

<!ELEMENT Detector ((Comment|Param|LIGO_LW)*)>
<!ATTLIST Detector 
         Name CDATA #IMPLIED>

<!ELEMENT AdcData ((AdcData|Comment|Param|Time|LIGO_LW|Array)*)>
<!ATTLIST AdcData 
         Name CDATA #IMPLIED>

<!ELEMENT AdcInterval ((AdcData|Comment|Time)*)>
<!ATTLIST AdcInterval 
         Name CDATA #IMPLIED
         StartTime CDATA #IMPLIED
         DeltaT CDATA #IMPLIED>

<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time 
         Name CDATA #IMPLIED
         Type (GPS|Unix|ISO-8601) "ISO-8601">
]>

<LIGO_LW>
   <Comment>metadata</Comment>
   <Table Name="processgroup:process:table">
      <Column Name="processgroup:process:program" Type="lstring"/>
      <Column Name="processgroup:process:version" Type="lstring"/>
      <Column Name="processgroup:process:cvs_repository" Type="lstring"/>
      <Column Name="processgroup:process:cvs_entry_time" Type="int_4s"/>
      <Column Name="processgroup:process:comment" Type="lstring"/>
      <Column Name="processgroup:process:is_online" Type="int_4s"/>
      <Column Name="processgroup:process:node" Type="lstring"/>
      <Column Name="processgroup:process:username" Type="lstring"/>
      <Column Name="processgroup:process:unix_procid" Type="int_4s"/>
      <Column Name="processgroup:process:start_time" Type="int_4s"/>
      <Column Name="processgroup:process:end_time" Type="int_4s"/>
      <Column Name="processgroup:process:jobid" Type="int_4s"/>
      <Column Name="processgroup:process:domain" Type="lstring"/>
      <Column Name="processgroup:process:ifos" Type="lstring"/>
      <Column Name="processgroup:process:process_id" Type="ilwd:char"/>
      <Stream Name="processgroup:process:table" Type="Local" Delimiter=",">
         "sire","1.15","/usr/local/cvs/lscsoft/lalapps/src/inspiral/sire.c\,v",769623277," ",0,"ldas-grid.ligo.caltech.edu","dbrown",23467,776376232,776376234,0,"lalapps","","process:process_id:0"
      </Stream>
   </Table>
   <Table Name="process_paramsgroup:process_params:table">
      <Column Name="process_paramsgroup:process_params:program" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:process_id" Type="ilwd:char"/>
      <Column Name="process_paramsgroup:process_params:param" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:type" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:value" Type="lstring"/>
      <Stream Name="process_paramsgroup:process_params:table" Type="Local" Delimiter=",">
         "sire","process:process_id:0","--playground-only","string"," ",
         "sire","process:process_id:0","--input","string","h1-inca_l1h1.files",
         "sire","process:process_id:0","--output","string","h1-inca_l1h1_inj_clust.xml",
         "sire","process:process_id:0","--debug-level","string","33",
         "sire","process:process_id:0","--injection-coincidence","int","5",
         "sire","process:process_id:0","--cluster-time","int","16",
         "sire","process:process_id:0","--cluster-algorithm","string","snr",
         "sire","process:process_id:0","--injection-file","string","HL-INJECTIONS_2375-729273613-5094000.xml"
      </Stream>
   </Table>
   <Table Name="sim_inspiralgroup:sim_inspiral:table">
      <Column Name="sim_inspiralgroup:sim_inspiral:process_id" Type="ilwd:char"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:waveform" Type="lstring"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:geocent_end_time" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:geocent_end_time_ns" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:h_end_time" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:h_end_time_ns" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:l_end_time" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:l_end_time_ns" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:end_time_gmst" Type="real_8"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:source" Type="lstring"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:mass1" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:mass2" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:eta" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:distance" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:longitude" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:latitude" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:inclination" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:coa_phase" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:polarization" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:eff_dist_h" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:eff_dist_l" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:simulation_id" Type="ilwd:char"/>
      <Stream Name="sim_inspiralgroup:sim_inspiral:table" Type="Local" Delimiter=",">
         "process:process_id:0","GeneratePPNtwoPN",729649919,575291157,729649919,589851038,729649919,586963755,1.0433322888500989e+01,"MW",8.226927e-01,9.537508e-01,2.486393e-01,4.613848e-02,5.536974e+00,-1.377090e+00,1.070415e+00,8.902087e-01,2.438556e+00,1.177795e-01,1.330057e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729674958,448174924,729674958,462302601,729674958,455204170,1.7407608178079958e+01,"MW",2.110491e-01,3.912427e-01,2.276228e-01,2.361401e-02,3.938535e+00,-1.258481e+00,2.776244e+00,4.614666e+00,3.995948e+00,3.532091e-02,4.550770e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729789768,656732321,729789768,674156788,729789768,667438697,1.3866494305307666e+00,"MW",8.917058e-01,6.394292e-01,2.432132e-01,4.272247e-02,6.636606e-01,-5.925696e-01,2.437540e+00,3.065538e-01,2.746196e+00,6.559622e-02,1.070199e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729796531,100872040,729796531,116792204,729796531,114090222,3.2702491827640268e+00,"MW",6.674920e-01,3.396972e-01,2.235198e-01,3.307845e-03,1.529683e+00,-1.627405e-01,1.164971e+00,3.535686e+00,7.011150e-01,7.602953e-03,8.327548e-03,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729802376,328663111,729802376,307846113,729802376,311432366,4.8983690450340509e+00,"MW",3.408363e-01,3.106623e-01,2.494637e-01,2.198385e-02,5.236537e+00,7.151765e-01,8.275104e-01,3.483059e+00,5.621437e+00,3.092586e-02,3.726821e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730273715,140897289,730273715,129090918,730273715,138323983,1.6184284365827011e+01,"MW",7.219793e-01,4.109949e-01,2.311645e-01,3.639233e-02,8.697089e-01,5.718859e-01,2.694590e+00,4.642105e+00,4.683925e-01,7.189897e-02,2.394016e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730496990,671339512,730496990,678973641,730496990,686516654,6.3750728561811973e+00,"MW",5.546100e-01,4.773628e-01,2.485992e-01,3.369792e-02,4.003227e+00,-2.294001e-01,6.600920e-01,3.943485e+00,5.470068e+00,1.149512e-01,5.898165e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730547730,137539387,730547730,131564484,730547730,124778477,2.0507957941219210e+01,"MW",3.894879e-01,3.852222e-01,2.499924e-01,3.169676e-02,4.797883e+00,3.440554e-01,1.609514e+00,1.130350e+00,7.305964e-01,1.701559e-01,2.078552e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730605295,781760693,730605295,801432777,730605295,802786249,1.2542195081176857e+01,"MW",9.676152e-01,5.691509e-01,2.331925e-01,2.151884e-02,4.839088e+00,-6.781250e-01,2.712147e+00,5.752896e+00,1.425783e+00,2.551358e-02,2.387862e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730700903,365319252,730700903,360356943,730700903,370087325,1.5172569644757443e+01,"MW",6.587099e-01,2.103656e-01,1.834653e-01,3.230770e-02,6.236485e+00,6.394392e-01,2.803668e+00,4.487288e+00,1.299758e+00,7.193711e-02,7.275327e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730713325,132064700,730713325,148819084,730713325,141708804,1.8632507548439833e+01,"MW",1.926584e-01,9.389115e-01,1.412700e-01,2.042087e-02,4.840602e+00,-1.151270e+00,1.821882e+00,1.420201e+00,5.173247e+00,6.592495e-02,7.774756e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730719626,747625947,730719626,766666405,730719626,763879079,2.0387748893056479e+01,"MW",4.920976e-01,4.063705e-01,2.477240e-01,4.981945e-02,6.116937e+00,-4.070434e-01,1.269509e+00,4.222919e+00,4.516657e+00,1.596729e-01,2.085920e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730911284,420159340,730911284,414501059,730911284,411018274,1.7717527439031335e+00,"MW",5.658423e-01,4.905418e-01,2.487298e-01,2.987881e-02,4.671537e+00,-4.936572e-01,1.640371e+00,3.077198e+00,9.512510e-01,2.032287e-01,1.671716e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731306019,365315914,731306019,384111052,731306019,382828681,1.5720556525844668e+01,"MW",9.784838e-01,2.771205e-01,1.719954e-01,1.046248e-02,5.848354e+00,-1.122893e+00,7.118651e-01,9.057677e-01,3.904781e+00,1.550035e-02,1.653180e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731580102,63742161,731580102,64347399,731580102,64465109,2.0063087653174168e+01,"MW",3.604050e-01,7.478197e-01,2.194482e-01,3.490343e-02,5.762198e+00,6.543639e-01,1.688678e+00,1.198373e+00,4.707859e+00,3.763405e-01,8.342610e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731586303,519413948,731586303,515262130,731586303,510958269,2.1790430615449118e+01,"MW",4.687778e-01,2.941813e-01,2.369079e-01,4.405782e-02,5.510778e+00,5.539181e-01,1.857652e+00,4.689622e+00,2.470467e+00,1.582990e-01,1.866177e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731598890,504378557,731598890,505110883,731598890,511992766,1.2963881099224090e+00,"MW",3.057767e-01,8.892432e-01,1.904034e-01,3.923721e-02,3.184994e+00,-2.501674e-01,1.602316e+00,4.399618e+00,2.130487e+00,2.061938e-01,6.769634e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731668934,476866007,731668934,458397670,731668934,465240103,2.0806317712561125e+01,"MW",9.856915e-01,2.544175e-01,1.630678e-01,1.097995e-02,2.582475e+00,8.766162e-01,1.244352e+00,1.347981e-02,5.361732e+00,2.580545e-02,4.005045e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731675326,432892561,731675326,427624507,731675326,422296423,2.2586722332562008e+01,"MW",8.926480e-01,4.693619e-01,2.258539e-01,1.807371e-02,4.084596e+00,-4.922282e-01,1.488068e+00,1.005925e+00,5.798977e+00,8.868223e-02,7.536618e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731701112,276728630,731701112,294891845,731701112,290508905,5.7690676505491139e+00,"MW",7.735451e-01,2.321372e-01,1.775451e-01,3.477781e-02,2.458329e+00,-1.350533e+00,1.855409e+00,5.110511e-01,1.002169e+00,8.394531e-02,9.492954e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731719769,43111086,731719769,59696005,731719769,59340767,1.0965691798316936e+01,"MW",1.704195e-01,7.302711e-01,1.534095e-01,1.618917e-02,5.049740e+00,-1.113638e+00,3.885053e-01,2.115152e-01,4.131777e+00,2.179141e-02,2.282509e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731828226,165385723,731828226,161700695,731828226,159436384,1.7175155135339335e+01,"MW",7.163215e-01,4.816845e-01,2.404101e-01,2.452105e-02,2.220517e+00,-5.781657e-01,1.425326e+00,8.005437e-01,2.806698e+00,3.515281e-01,1.626096e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731879189,945458651,731879189,948763093,731879189,957845863,7.3705202096493707e+00,"MW",6.995283e-01,4.922509e-01,2.424377e-01,3.296418e-02,4.264090e+00,6.131073e-02,4.536463e-01,9.582439e-01,1.227399e+00,2.007273e-01,6.277601e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731885722,970247746,731885722,990491702,731885722,985414837,9.1902178828542436e+00,"MW",9.247231e-01,9.146960e-01,2.499926e-01,2.577493e-02,3.044822e+00,-9.688836e-01,2.799523e+00,1.428410e+00,3.476069e+00,2.864904e-02,3.718714e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731892203,924365520,731892203,939307363,731892203,931396863,1.0995411885595985e+01,"MW",5.596641e-01,8.903620e-01,2.369968e-01,3.324667e-02,2.561057e+00,-1.093482e+00,6.895694e-01,3.696517e+00,4.280159e+00,5.749052e-02,8.063591e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731898186,856838942,731898186,845563927,731898186,854953310,1.2661887760923969e+01,"MW",2.586064e-01,8.366197e-01,1.803681e-01,4.191535e-02,5.970838e+00,7.985083e-01,1.056346e+00,1.851049e+00,4.516672e+00,1.136439e-01,1.986415e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731911191,734116554,731911191,747907114,731911191,751631590,1.6284244275742935e+01,"MW",4.578967e-01,6.369029e-01,2.433165e-01,3.271374e-02,5.578819e+00,2.616266e-02,2.422832e+00,4.455264e-01,4.100823e-01,6.050896e-02,5.076588e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731917518,40860176,731917518,47219679,731917518,48683402,1.8046363053052790e+01,"MW",9.511867e-01,3.755850e-01,2.029465e-01,8.279233e-03,1.570862e+00,-8.169876e-01,2.563788e+00,2.768158e+00,5.881621e+00,1.988861e-02,2.112170e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731949432,265460968,731949432,263658770,731949432,254261847,2.9356971798050733e+00,"MW",8.004861e-01,8.913803e-01,2.492784e-01,3.330457e-02,6.261988e+00,-1.416268e-01,1.204883e+00,4.538537e+00,2.160186e-03,4.673684e-01,1.145166e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",731993873,914840698,731993873,901983532,731993873,895666269,1.5314399012658331e+01,"MW",5.418361e-01,9.119768e-01,2.337947e-01,2.662286e-02,2.710783e+00,1.722184e-01,1.193310e+00,4.745440e+00,2.286649e+00,1.045114e-01,7.602485e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732350610,53745985,732350610,38411895,732350610,43445685,1.8679079602716698e+01,"MW",8.691430e-01,4.268512e-01,2.208827e-01,4.167494e-02,1.247491e+00,1.519491e+00,2.018771e+00,6.240579e+00,1.818356e+00,1.308607e-01,1.546862e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732440066,160610199,732440066,152905962,732440066,146814124,1.9596032261343467e+01,"MW",2.475948e-01,6.637378e-01,1.978719e-01,1.144372e-02,4.527010e+00,4.381014e-01,2.129913e+00,4.261789e+00,2.124613e+00,3.717764e-02,2.729349e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732496841,493116498,732496841,487448599,732496841,492940962,1.1410137326986426e+01,"MW",6.818454e-01,7.720452e-01,2.490378e-01,3.361747e-02,4.232272e+00,1.026997e+00,1.107445e+00,5.191552e+00,5.702138e+00,1.754498e-01,2.042793e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732548039,220707893,732548039,226839592,732548039,216850790,1.6706657460373309e+00,"MW",8.873015e-01,4.496770e-01,2.232148e-01,3.394659e-02,6.062181e+00,-5.444577e-01,1.013410e+00,1.415981e+00,3.003841e-01,1.340586e-01,1.853411e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732586026,872081041,732586026,857637640,732586026,858897123,1.2251681899457342e+01,"MW",3.944833e-01,2.508974e-01,2.376254e-01,3.215029e-02,8.348753e-01,2.420896e-02,8.115374e-01,2.108354e+00,1.035949e+00,6.417939e-02,6.350877e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732637548,450491905,732637548,446184893,732637548,438671313,2.6024151803470321e+00,"MW",7.662438e-01,4.497582e-01,2.330652e-01,3.758702e-02,5.481857e+00,-4.457987e-01,2.002604e+00,4.514453e+00,2.597551e+00,1.257334e-01,1.071023e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733025725,790952921,733025725,786906764,733025725,796613914,1.4724674853483835e+01,"MW",5.241309e-01,6.103529e-01,2.485560e-01,2.548856e-02,6.079392e+00,6.090388e-01,2.742447e+00,2.704360e+00,5.096334e+00,5.937848e-02,5.648623e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733076545,886349559,733076545,880398483,733076545,872369663,4.8800182411488562e+00,"MW",3.464294e-01,9.364135e-01,1.971222e-01,2.618207e-02,6.225370e+00,-2.882390e-01,1.957445e+00,2.416198e-02,2.613904e+00,8.754868e-02,6.874852e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733089500,604736090,733089500,584409950,733089500,586669183,8.4884035833055780e+00,"MW",5.615545e-01,5.523808e-01,2.499831e-01,3.396202e-02,3.934476e-01,1.061194e+00,1.064448e+00,2.554481e+00,1.825916e+00,7.202914e-02,8.108220e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733452474,43040156,733452474,61090629,733452474,59777570,1.3590410990450117e+01,"MW",3.902662e-01,4.091311e-01,2.498608e-01,1.478064e-02,5.435207e+00,-1.166246e+00,1.907567e+00,5.431763e+00,5.962329e+00,3.357763e-02,3.989007e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733535363,144450665,733535363,144341077,733535363,141095456,1.2678201070249909e+01,"MW",5.616885e-01,6.166061e-01,2.494569e-01,1.410808e-02,3.427302e+00,5.144951e-01,1.131503e+00,5.442236e+00,2.206209e+00,5.592578e-02,5.012960e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733592777,584860802,733592777,602271519,733592777,597525249,4.6703221577033398e+00,"MW",2.369943e-01,3.636636e-01,2.388820e-01,3.490702e-02,1.970300e+00,-1.407817e+00,1.065318e+00,3.089060e+00,5.154978e+00,7.923706e-02,1.030127e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733637658,378625393,733637658,395356589,733637658,398650725,1.7171342514591913e+01,"MW",3.265913e-01,6.141444e-01,2.266417e-01,2.280812e-02,5.908215e+00,-2.156576e-01,8.564478e-01,1.474624e+00,5.936482e+00,4.306366e-02,3.690166e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733700930,444103956,733700930,436552657,733700930,432790992,1.0795036592177219e+01,"MW",6.607442e-01,6.466592e-01,2.499710e-01,3.994041e-02,8.273494e-01,-3.973731e-01,7.077277e-01,8.443308e-01,2.735925e+00,1.247716e-01,9.547654e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733707206,188588023,733707206,173831037,733707206,181201371,1.2543071851970421e+01,"MW",6.339387e-01,3.554589e-01,2.301945e-01,1.203861e-02,5.992429e+00,1.206297e+00,3.190649e-01,4.814211e+00,5.644020e+00,1.709109e-02,2.262497e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733732907,61517715,733732907,63365717,733732907,54237429,1.9701749521191751e+01,"MW",6.489813e-01,5.970532e-01,2.495658e-01,3.947278e-02,4.673977e+00,-9.262000e-02,2.156098e+00,6.049275e+00,3.682944e+00,4.869906e-01,1.857082e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733911090,86532712,733911090,101628619,733911090,93700761,2.1332547845401699e+01,"MW",4.861832e-01,3.067687e-01,2.372015e-01,1.444335e-02,5.298523e+00,-1.081179e+00,1.708076e+00,2.715820e+00,4.224196e+00,1.213474e-01,1.760737e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",734140883,417647362,734140883,428838315,734140883,419483308,1.3338793514557183e+01,"MW",2.848870e-01,9.377469e-01,1.787168e-01,4.437065e-02,3.229618e+00,-5.557189e-01,2.807712e+00,4.233352e+00,1.188650e+00,8.816207e-02,3.165816e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",734331972,220533371,734331972,236081891,734331972,234619721,1.8564345373776224e+01,"MW",1.868326e-01,6.391135e-01,1.750360e-01,6.269368e-03,9.866967e-01,-1.240611e+00,5.266154e-01,2.967463e+00,2.538905e+00,9.597654e-03,1.074148e-02,"sim_inspiral:simulation_id:0"
      </Stream>
   </Table>
   <Table Name="sngl_inspiralgroup:sngl_inspiral:table">
      <Column Name="sngl_inspiralgroup:sngl_inspiral:process_id" Type="ilwd:char"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ifo" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:search" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:channel" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_gmst" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:template_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:event_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:amplitude" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eff_distance" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:coa_phase" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass1" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mchirp" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eta" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau4" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau5" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ttotal" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:f_final" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:snr" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq_dof" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:sigmasq" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:alpha" Type="real_4"/>
      <Stream Name="sngl_inspiralgroup:sngl_inspiral:table" Type="Local" Delimiter=",">
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",729649919,590332031,1.0433327079721623e+01,729649919,590332031,4.5788125991821289e+00,9.7656250000000000e-04,0.000000e+00,1.151149e-01,-5.125322e-01,8.851236e-01,8.851236e-01,7.705448e-01,2.500000e-01,4.637152e+00,3.508854e-01,2.553962e-01,1.643863e-02,0.000000e+00,4.749080e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.646135e+01,5.152314e+01,15,1.7616858731080715e+01,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",729674958,462890625,1.7407612279649410e+01,729674958,462890625,3.0896068572998047e+01,9.7656250000000000e-04,0.000000e+00,3.613528e-02,2.498467e+00,3.692017e-01,2.223423e-01,2.478415e-01,2.345912e-01,3.071080e+01,1.102669e+00,5.652069e-01,2.461736e-02,0.000000e+00,3.127288e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.588669e+01,1.161226e+02,15,2.7493904562444809e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",729789768,674316406,1.3866543277560008e+00,729789768,674316406,6.0186204910278320e+00,1.2207031250000000e-03,0.000000e+00,6.577986e-02,1.320789e+00,8.088265e-01,7.026995e-01,6.559820e-01,2.487676e-01,6.064030e+00,4.124979e-01,2.851716e-01,1.737853e-02,0.000000e+00,6.208735e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.752161e+01,5.455098e+01,15,9.7716575113941087e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",729796531,116699218,3.2702535869056981e+00,729796531,116699218,1.3273748397827148e+01,1.2207031250000000e-03,0.000000e+00,7.736461e-03,2.598355e+00,7.364998e-01,3.115987e-01,4.096195e-01,2.089123e-01,1.329271e+01,6.815631e-01,4.334559e-01,2.189681e-02,0.000000e+00,1.356271e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.570916e+02,2.896101e+03,15,3.9560379120769897e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",729802376,308105468,4.8983633185302216e+00,729802376,308105468,2.4733547210693359e+01,1.2207031250000000e-03,0.000000e+00,3.063748e-02,1.545792e+00,3.253470e-01,3.253470e-01,2.832310e-01,2.500000e-01,2.458554e+01,9.546021e-01,4.977209e-01,2.294834e-02,0.000000e+00,2.506537e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.929485e+01,4.843665e+01,15,2.2809144275196394e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",730273715,130371093,1.6184281429731183e+01,730273715,130371093,1.0541606903076172e+01,9.7656250000000000e-04,0.000000e+00,7.472699e-02,-1.396479e+00,5.408440e-01,5.408440e-01,4.708320e-01,2.500000e-01,1.053912e+01,5.742449e-01,3.546792e-01,1.937207e-02,0.000000e+00,1.077806e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.133992e+01,4.442712e+01,15,5.4846718761119728e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",730496990,678222656,6.3750747724870838e+00,730496990,678222656,1.1464313507080078e+01,1.4648437500000000e-03,0.000000e+00,1.146829e-01,-6.853817e-02,6.861286e-01,3.910985e-01,4.474593e-01,2.312475e-01,1.147251e+01,6.122929e-01,3.844989e-01,2.033851e-02,0.000000e+00,1.172065e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.258527e+01,2.375244e+01,15,6.7088421395108879e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",730547730,131835937,2.0507956349903509e+01,730547730,131835937,1.8470403671264648e+01,1.4648437500000000e-03,0.000000e+00,1.424951e-01,-1.036917e+00,3.873209e-01,3.873209e-01,3.371824e-01,2.500000e-01,1.838540e+01,8.018594e-01,4.431014e-01,2.165259e-02,0.000000e+00,1.876580e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.395555e+01,4.653064e+01,15,3.9545176897051157e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",730605295,801025390,1.2542200449075963e+01,730605295,801025390,6.2297558784484863e+00,1.2207031250000000e-03,0.000000e+00,2.559396e-02,1.307834e+00,1.129013e+00,4.957467e-01,6.406451e-01,2.120218e-01,6.307908e+00,4.345439e-01,3.188628e-01,1.873883e-02,0.000000e+00,6.442328e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.439779e+02,3.321351e+02,15,1.3578962018814527e+01,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",730700903,359619140,1.5172568064642450e+01,730700903,359619140,2.0674938201904297e+01,1.7089843750000000e-03,0.000000e+00,7.793576e-02,-4.212521e-01,7.121245e-01,1.974280e-01,3.140605e-01,1.699453e-01,2.069628e+01,9.283249e-01,5.856652e-01,2.643706e-02,0.000000e+00,2.106538e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.775637e+01,3.644455e+01,15,4.6794938233423506e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",730713325,150390625,1.8632512658590244e+01,730713325,150390625,1.7193080902099609e+01,1.2207031250000000e-03,0.000000e+00,6.967956e-02,1.177226e+00,8.864123e-01,2.016052e-01,3.499092e-01,1.509613e-01,1.728445e+01,8.566187e-01,5.850874e-01,2.714766e-02,0.000000e+00,1.758313e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.300382e+01,4.839525e+01,15,5.2885826437428296e+00,0.000000e+00,
         "process:process_id:0","H1","FindChirpSPtwoPN","LSC-AS_Q",730719626,766357421,2.0387754115271900e+01,730719626,766357421,1.4529937744140625e+01,1.7089843750000000e-03,0.000000e+00,1.717926e-01,3.924193e-02,5.434265e-01,3.698851e-01,3.888667e-01,2.409737e-01,1.449595e+01,6.995451e-01,4.119028e-01,2.095296e-02,0.000000e+00,1.480454e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.491162e+01,2.957422e+01,15,6.5623336986762784e+00,0.000000e+00,