<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE LIGO_LW [
<!ELEMENT LIGO_LW ((LIGO_LW|Comment|Param|Table|Array|Stream|IGWDFrame|AdcData|AdcInterval|Time|Detector)*)>
<!ATTLIST LIGO_LW
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Comment (#PCDATA)>

<!ELEMENT Param (#PCDATA|Comment)*>
<!ATTLIST Param 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED
         Unit CDATA #IMPLIED
         DataUnit CDATA #IMPLIED>

<!ELEMENT Table (Comment?,Column*,Stream?)>
<!ATTLIST Table 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Column EMPTY>
<!ATTLIST Column
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Array (Dim*,Stream?)>
<!ATTLIST Array 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Dim (#PCDATA)>
<!ATTLIST Dim 
         Name  CDATA #IMPLIED
         Unit CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED>

<!ELEMENT Stream (#PCDATA)>
<!ATTLIST Stream 
         Name      CDATA #IMPLIED
         Type      (Remote|Local) "Local"
         Delimiter CDATA ","
         Encoding  CDATA #IMPLIED
         Content   CDATA #IMPLIED>

<!ELEMENT IGWDFrame ((Comment|Param|Time|Detector|AdcData|LIGO_LW|Stream?|Array|IGWDFrame)*)>
<!ATTLIST IGWDFrame 
         Name CDATA #IMPLIED>

<!ELEMENT Detector ((Comment|Param|LIGO_LW)*)>
<!ATTLIST Detector 
         Name CDATA #IMPLIED>

<!ELEMENT AdcData ((AdcData|Comment|Param|Time|LIGO_LW|Array)*)>
<!ATTLIST AdcData 
         Name CDATA #IMPLIED>

<!ELEMENT AdcInterval ((AdcData|Comment|Time)*)>
<!ATTLIST AdcInterval 
         Name CDATA #IMPLIED
         StartTime CDATA #IMPLIED
         DeltaT CDATA #IMPLIED>

<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time 
         Name CDATA #IMPLIED
         Type (GPS|Unix|ISO-8601) "ISO-8601">
]>

<LIGO_LW>
   <Comment>metadata</Comment>
   <Table Name="processgroup:process:table">
      <Column Name="processgroup:process:program" Type="lstring"/>
      <Column Name="processgroup:process:version" Type="lstring"/>
      <Column Name="processgroup:process:cvs_repository" Type="lstring"/>
      <Column Name="processgroup:process:cvs_entry_time" Type="int_4s"/>
      <Column Name="processgroup:process:comment" Type="lstring"/>
      <Column Name="processgroup:process:is_online" Type="int_4s"/>
      <Column Name="processgroup:process:node" Type="lstring"/>
      <Column Name="processgroup:process:username" Type="lstring"/>
      <Column Name="processgroup:process:unix_procid" Type="int_4s"/>
      <Column Name="processgroup:process:start_time" Type="int_4s"/>
      <Column Name="processgroup:process:end_time" Type="int_4s"/>
      <Column Name="processgroup:process:jobid" Type="int_4s"/>
      <Column Name="processgroup:process:domain" Type="lstring"/>
      <Column Name="processgroup:process:ifos" Type="lstring"/>
      <Column Name="processgroup:process:process_id" Type="ilwd:char"/>
      <Stream Name="processgroup:process:table" Type="Local" Delimiter=",">
         "sire","1.15","/usr/local/cvs/lscsoft/lalapps/src/inspiral/sire.c\,v",769623277," ",0,"ldas-grid.ligo.caltech.edu","dbrown",23458,776376229,776376231,0,"lalapps","","process:process_id:0"
      </Stream>
   </Table>
   <Table Name="process_paramsgroup:process_params:table">
      <Column Name="process_paramsgroup:process_params:program" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:process_id" Type="ilwd:char"/>
      <Column Name="process_paramsgroup:process_params:param" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:type" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:value" Type="lstring"/>
      <Stream Name="process_paramsgroup:process_params:table" Type="Local" Delimiter=",">
         "sire","process:process_id:0","--playground-only","string"," ",
         "sire","process:process_id:0","--input","string","l1-inca_l1h2.files",
         "sire","process:process_id:0","--output","string","l1-inca_l1h2_inj.xml",
         "sire","process:process_id:0","--summary-file","string","l1-inca_l1h2_inj.txt",
         "sire","process:process_id:0","--debug-level","string","33",
         "sire","process:process_id:0","--missed-injections","string","l1-inca_l1h2_missed.xml",
         "sire","process:process_id:0","--injection-coincidence","int","5",
         "sire","process:process_id:0","--injection-file","string","HL-INJECTIONS_2375-729273613-5094000.xml"
      </Stream>
   </Table>
   <Table Name="sim_inspiralgroup:sim_inspiral:table">
      <Column Name="sim_inspiralgroup:sim_inspiral:process_id" Type="ilwd:char"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:waveform" Type="lstring"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:geocent_end_time" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:geocent_end_time_ns" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:h_end_time" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:h_end_time_ns" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:l_end_time" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:l_end_time_ns" Type="int_4s"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:end_time_gmst" Type="real_8"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:source" Type="lstring"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:mass1" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:mass2" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:eta" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:distance" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:longitude" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:latitude" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:inclination" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:coa_phase" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:polarization" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:eff_dist_h" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:eff_dist_l" Type="real_4"/>
      <Column Name="sim_inspiralgroup:sim_inspiral:simulation_id" Type="ilwd:char"/>
      <Stream Name="sim_inspiralgroup:sim_inspiral:table" Type="Local" Delimiter=",">
         "process:process_id:0","GeneratePPNtwoPN",729439438,240201950,729439438,231333739,729439438,231520819,2.3806207910879618e+01,"MW",4.427303e-01,5.472688e-01,2.472124e-01,3.446198e-02,3.811759e+00,-2.912904e-01,1.135639e+00,4.740113e+00,5.895225e-01,1.360390e-01,1.386824e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729483905,360875607,729483905,373583009,729483905,379979808,1.2192004481073884e+01,"MW",2.003722e-01,5.036674e-01,2.036044e-01,2.575655e-02,5.093754e+00,-2.077008e-01,3.002823e+00,5.498539e+00,4.919199e+00,4.203141e-02,2.892093e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729490687,143688679,729490687,153401615,729490687,144476359,1.4080990790931715e+01,"MW",3.719227e-01,5.386242e-01,2.416206e-01,2.257303e-02,3.507662e+00,-3.439492e-01,2.540557e+00,4.602389e+00,3.633599e+00,5.796825e-02,2.587847e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729509340,612858415,729509340,605065617,729509340,604094710,1.9276696523705290e+01,"MW",1.669840e-01,8.994994e-01,1.320589e-01,1.444521e-02,4.998367e+00,8.908629e-01,1.436993e+00,3.039185e+00,4.892490e+00,1.780952e-01,1.245479e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729566881,383426666,729566881,387120886,729566881,394353214,1.1304005409624013e+01,"MW",3.584151e-01,2.018502e-01,2.304772e-01,2.154443e-02,4.558008e+00,4.996839e-01,1.447180e+00,4.378263e+00,3.443874e+00,8.826820e-02,7.062165e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729853598,465760231,729853598,457665362,729853598,451562000,1.9165696451494263e+01,"MW",4.571671e-01,4.559518e-01,2.499996e-01,2.290894e-02,4.384977e+00,4.382727e-01,1.305555e+00,2.015706e+00,5.600554e+00,1.199812e-01,1.180353e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",729859731,876122832,729859731,879446198,729859731,885613309,2.0874086180999875e+01,"MW",9.067869e-01,6.679645e-01,2.442500e-01,9.581940e-03,1.977864e+00,-3.740783e-01,1.728560e+00,2.151243e+00,1.274505e-02,1.292590e-01,3.964506e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730191123,129814148,730191123,149327751,730191123,151015643,1.7179245332831311e+01,"MW",3.077084e-01,9.414036e-01,1.856575e-01,5.299038e-02,6.007405e+00,-5.904682e-01,1.498880e+00,1.113302e+00,6.132928e+00,1.975951e-01,1.828930e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730535084,855745316,730535084,872349305,730535084,872443402,1.6985762541517616e+01,"MW",3.567013e-01,9.930013e-01,1.944367e-01,1.482160e-02,3.286653e-01,-1.065410e+00,2.347675e+00,1.173969e+00,3.014355e+00,2.487736e-02,2.526428e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",730541605,856745720,730541605,869953802,730541605,861149450,1.8802111127724249e+01,"MW",1.695767e-01,3.562952e-01,2.184823e-01,2.691857e-02,4.814795e+00,-5.750162e-01,1.845536e+00,2.204749e+00,4.737928e+00,8.384076e-02,2.356323e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732153032,423493147,732153032,426563428,732153032,435167452,1.1646140746759871e+01,"MW",7.793598e-01,6.944638e-01,2.491705e-01,1.437997e-02,4.926633e+00,4.099172e-01,2.700860e+00,3.387118e+00,3.714157e+00,3.180794e-02,2.440500e-02,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732650264,675069332,732650264,686085701,732650264,683518646,6.1443708579200838e+00,"MW",9.313419e-01,2.771716e-01,1.767481e-01,4.361798e-02,5.015642e+00,-1.230050e+00,1.032905e+00,3.646403e-01,1.191460e+00,1.412418e-01,1.969976e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",732879062,472818971,732879062,488323101,732879062,480020608,2.1873322359079289e+01,"MW",6.230013e-01,8.424091e-01,2.443956e-01,5.493292e-02,5.711236e+00,-7.365342e-01,1.971240e+00,6.032604e+00,3.982862e+00,1.762930e-01,3.577754e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",733713674,44290066,733713674,60691476,733713674,54713493,1.4344617431701886e+01,"MW",3.078850e-01,1.670166e-01,2.280032e-01,3.306786e-02,3.716180e+00,-1.361920e+00,1.978640e+00,7.365675e-01,2.072798e+00,8.659858e-02,1.013387e-01,"sim_inspiral:simulation_id:0",
         "process:process_id:0","GeneratePPNtwoPN",734350994,693580151,734350994,701464567,734350994,709634575,2.3862832832125324e+01,"MW",5.088500e-01,2.918382e-01,2.316355e-01,4.126958e-02,2.018877e+00,5.390506e-03,8.681108e-01,1.483522e+00,3.395334e+00,1.333810e-01,7.645407e-02,"sim_inspiral:simulation_id:0"
      </Stream>
   </Table>
   <Table Name="sngl_inspiralgroup:sngl_inspiral:table">
      <Column Name="sngl_inspiralgroup:sngl_inspiral:process_id" Type="ilwd:char"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ifo" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:search" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:channel" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_gmst" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:template_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:event_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:amplitude" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eff_distance" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:coa_phase" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass1" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mchirp" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eta" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau4" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau5" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ttotal" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:f_final" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:snr" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq_dof" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:sigmasq" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:alpha" Type="real_4"/>
      <Stream Name="sngl_inspiralgroup:sngl_inspiral:table" Type="Local" Delimiter=",">
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,226562500,2.3806204111886522e+01,729439438,226562500,1.2331829071044922e+01,7.3242187500000000e-04,0.000000e+00,1.593855e-01,-1.798098e+00,9.719158e-01,2.671776e-01,4.266153e-01,1.691300e-01,1.242188e+01,6.841457e-01,4.788731e-01,2.393011e-02,0.000000e+00,1.265108e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.076585e+01,4.110982e+02,15,2.4045576473260667e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,226806640,2.3806204179123871e+01,729439438,226806640,1.2332779884338379e+01,2.1972656250000000e-03,0.000000e+00,1.450764e-01,3.120733e+00,8.046139e-01,3.131271e-01,4.276778e-01,2.016628e-01,1.237049e+01,6.573341e-01,4.301869e-01,2.193665e-02,0.000000e+00,1.261957e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.387045e+01,2.340219e+02,15,2.4145470453419225e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,227294921,2.3806204324811699e+01,729439438,227294921,1.2341042518615723e+01,7.3242187500000000e-04,0.000000e+00,1.602314e-01,3.044349e-01,9.710351e-01,2.671621e-01,4.264301e-01,1.692116e-01,1.243087e+01,6.843682e-01,4.788731e-01,2.392764e-02,0.000000e+00,1.266029e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.059235e+01,3.968315e+02,15,2.4028189935161869e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,228271484,2.3806204593765241e+01,729439438,228271484,1.2341999053955078e+01,1.7089843750000000e-03,0.000000e+00,1.347399e-01,9.476207e-02,8.037810e-01,3.131480e-01,4.274913e-01,2.017605e-01,1.237948e+01,6.575573e-01,4.301869e-01,2.193491e-02,0.000000e+00,1.262878e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.645557e+01,9.114744e+01,15,2.4127926687501382e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,228271484,2.3806204593765241e+01,729439438,228271484,1.2350255012512207e+01,4.8828125000000000e-04,0.000000e+00,1.700401e-01,2.813722e+00,9.701555e-01,2.671466e-01,4.262451e-01,1.692932e-01,1.243986e+01,6.845906e-01,4.788731e-01,2.392517e-02,0.000000e+00,1.266950e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.881723e+01,4.836907e+02,15,2.4010814831813551e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,229248046,2.3806204862718779e+01,729439438,229248046,1.2350247383117676e+01,2.4414062500000000e-04,0.000000e+00,1.712856e-01,1.240497e+00,5.610918e-01,4.331475e-01,4.284534e-01,2.458600e-01,1.233318e+01,6.327780e-01,3.815006e-01,2.012343e-02,0.000000e+00,1.260458e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.873114e+01,5.546955e+02,15,2.4218498487334362e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,229248046,2.3806204862718779e+01,729439438,229248046,1.2351212501525879e+01,9.7656250000000000e-04,0.000000e+00,1.430446e-01,2.688888e+00,8.029491e-01,3.131690e-01,4.273051e-01,2.018582e-01,1.238847e+01,6.577804e-01,4.301869e-01,2.193317e-02,0.000000e+00,1.263800e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.432661e+01,2.487357e+02,15,2.4110408649772111e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,229980468,2.3806205064434973e+01,729439438,229980468,1.2360424041748047e+01,4.8828125000000000e-04,0.000000e+00,1.618722e-01,-1.470255e+00,8.021182e-01,3.131902e-01,4.271190e-01,2.019559e-01,1.239747e+01,6.580034e-01,4.301869e-01,2.193143e-02,0.000000e+00,1.264721e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.032303e+01,4.900792e+02,15,2.4092919198919031e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,230224609,2.3806205131676460e+01,729439438,230224609,1.2359361648559570e+01,1.4648437500000000e-03,0.000000e+00,1.477844e-01,-1.657420e+00,4.920539e-01,4.920538e-01,4.283578e-01,2.500000e-01,1.233777e+01,6.311848e-01,3.777536e-01,1.999229e-02,0.000000e+00,1.261120e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.329387e+01,3.066254e+02,15,2.4209487903959253e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,230224609,2.3806205131676460e+01,729439438,230224609,1.2359464645385742e+01,1.7089843750000000e-03,0.000000e+00,1.422610e-01,-2.545191e+00,5.597534e-01,4.337613e-01,4.282661e-01,2.459795e-01,1.234218e+01,6.330038e-01,3.815006e-01,2.012247e-02,0.000000e+00,1.261380e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.458035e+01,2.280838e+02,15,2.4200848949974617e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,230468750,2.3806205198913812e+01,729439438,230468750,1.2369637489318848e+01,0.0000000000000000e+00,0.000000e+00,1.700395e-01,2.341481e-01,8.012882e-01,3.132116e-01,4.269332e-01,2.020536e-01,1.240646e+01,6.582264e-01,4.301869e-01,2.192970e-02,0.000000e+00,1.265643e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.885608e+01,5.400833e+02,15,2.4075449758879284e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,231445312,2.3806205479076340e+01,729439438,231445312,1.2368450164794922e+01,1.4648437500000000e-03,0.000000e+00,1.308095e-01,1.226870e+00,4.918388e-01,4.918387e-01,4.281705e-01,2.500000e-01,1.234677e+01,6.314609e-01,3.778638e-01,1.999521e-02,0.000000e+00,1.262036e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.760063e+01,5.294460e+01,15,2.4191852660037604e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,231445312,2.3806205479076340e+01,729439438,231445312,1.2368683815002441e+01,1.4648437500000000e-03,0.000000e+00,1.299351e-01,4.029305e-01,5.584033e-01,4.343880e-01,4.280789e-01,2.460990e-01,1.235117e+01,6.332296e-01,3.815006e-01,2.012150e-02,0.000000e+00,1.262302e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.784692e+01,3.635501e+01,15,2.4183230858178682e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,232421875,2.3806205748029882e+01,729439438,232421875,1.2377544403076172e+01,9.7656250000000000e-04,0.000000e+00,1.362003e-01,-2.464670e+00,4.916239e-01,4.916239e-01,4.279834e-01,2.500000e-01,1.235576e+01,6.317369e-01,3.779739e-01,1.999812e-02,0.000000e+00,1.262952e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.609926e+01,1.450523e+02,15,2.4174240285616907e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,232421875,2.3806205748029882e+01,729439438,232421875,1.2377904891967773e+01,9.7656250000000000e-04,0.000000e+00,1.409134e-01,3.027861e+00,5.570407e-01,4.350280e-01,4.278920e-01,2.462185e-01,1.236016e+01,6.334553e-01,3.815006e-01,2.012054e-02,0.000000e+00,1.263224e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.488564e+01,2.233365e+02,15,2.4165627059820839e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,233642578,2.3806206084224915e+01,729439438,233642578,1.2386626243591309e+01,7.3242187500000000e-04,0.000000e+00,1.621585e-01,3.602039e-01,4.914093e-01,4.914093e-01,4.277966e-01,2.500000e-01,1.236476e+01,6.320127e-01,3.780839e-01,2.000103e-02,0.000000e+00,1.263869e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.030949e+01,4.611082e+02,15,2.4156656498072397e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729439438,233642578,2.3806206084224915e+01,729439438,233642578,1.2387128829956055e+01,2.4414062500000000e-04,0.000000e+00,1.704706e-01,-4.279498e-01,5.556652e-01,4.356821e-01,4.277053e-01,2.463379e-01,1.236916e+01,6.336810e-01,3.815006e-01,2.011958e-02,0.000000e+00,1.264146e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.882648e+01,5.372579e+02,15,2.4148054707026809e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,375976562,1.2192008683503502e+01,729483905,375976562,2.6534990310668945e+01,1.7089843750000000e-03,0.000000e+00,3.454956e-02,1.953596e-01,5.522804e-01,1.856457e-01,2.709593e-01,1.882863e-01,2.646922e+01,1.052221e+00,6.076915e-01,2.638640e-02,0.000000e+00,2.694013e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.797286e+01,3.000116e+03,15,9.2380965511035740e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,377685546,1.2192009154173235e+01,729483905,377685546,2.6544406890869141e+01,1.9531250000000000e-03,0.000000e+00,3.007397e-02,-2.599973e+00,5.520229e-01,1.856459e-01,2.709026e-01,1.883301e-01,2.647844e+01,1.052390e+00,6.076915e-01,2.638526e-02,0.000000e+00,2.694953e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.010473e+02,8.590087e+02,15,9.2348722304016082e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,379150390,1.2192009568814601e+01,729483905,379150390,2.6553796768188477e+01,1.4648437500000000e-03,0.000000e+00,2.896192e-02,6.762464e-01,5.517656e-01,1.856462e-01,2.708460e-01,1.883738e-01,2.648767e+01,1.052558e+00,6.076915e-01,2.638413e-02,0.000000e+00,2.695892e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.049089e+02,3.313487e+02,15,9.2316566857494564e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,380126953,1.2192009837768143e+01,729483905,380126953,2.6563196182250977e+01,9.7656250000000000e-04,0.000000e+00,3.255767e-02,-3.003616e+00,5.515085e-01,1.856465e-01,2.707894e-01,1.884176e-01,2.649690e+01,1.052727e+00,6.076915e-01,2.638301e-02,0.000000e+00,2.696832e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.330626e+01,2.471579e+03,15,9.2284411410973046e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,380615234,1.2192009972246984e+01,729483905,380615234,2.6569482803344727e+01,1.4648437500000000e-03,0.000000e+00,3.196785e-02,-2.542938e+00,4.551657e-01,2.187103e-01,2.710861e-01,2.192193e-01,2.644859e+01,1.020493e+00,5.545129e-01,2.459351e-02,0.000000e+00,2.693916e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.511459e+01,2.182780e+03,15,9.2453011029315562e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,381591796,1.2192010252405371e+01,729483905,381591796,2.6578876495361328e+01,1.2207031250000000e-03,0.000000e+00,2.892411e-02,6.621216e-02,4.549090e-01,2.187319e-01,2.710293e-01,2.192703e-01,2.645782e+01,1.020662e+00,5.545129e-01,2.459272e-02,0.000000e+00,2.694856e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.051053e+02,2.709334e+02,15,9.2420750270196272e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,382080078,1.2192010386884213e+01,729483905,382080078,2.6575355529785156e+01,4.8828125000000000e-04,0.000000e+00,3.632615e-02,-2.374479e+00,3.116746e-01,3.116746e-01,2.713285e-01,2.500000e-01,2.640922e+01,9.964783e-01,5.121724e-01,2.327911e-02,0.000000e+00,2.691681e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.376539e+01,3.626622e+03,15,9.2590824264907656e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,382812500,1.2192010588600404e+01,729483905,382812500,2.6584692001342773e+01,7.3242187500000000e-04,0.000000e+00,3.512565e-02,-2.610391e-01,3.116092e-01,3.116092e-01,2.712716e-01,2.500000e-01,2.641845e+01,9.966872e-01,5.122440e-01,2.328074e-02,0.000000e+00,2.692617e+01,0.000000e+00,0.000000e+00,0.000000e+00,8.661311e+01,3.394900e+03,15,9.2558464043890467e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,383056640,1.2192010655841894e+01,729483905,383056640,2.6588283538818359e+01,1.2207031250000000e-03,0.000000e+00,3.057473e-02,-2.954601e+00,4.546524e-01,2.187536e-01,2.709726e-01,2.193213e-01,2.646705e+01,1.020832e+00,5.545129e-01,2.459193e-02,0.000000e+00,2.695796e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.941374e+01,1.119159e+03,15,9.2388524615276229e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,383300781,1.2192010723079244e+01,729483905,383300781,2.6594001770019531e+01,7.3242187500000000e-04,0.000000e+00,3.236007e-02,1.502182e+00,3.115439e-01,3.115439e-01,2.712147e-01,2.500000e-01,2.642768e+01,9.968961e-01,5.123156e-01,2.328236e-02,0.000000e+00,2.693554e+01,0.000000e+00,0.000000e+00,0.000000e+00,9.399890e+01,2.222338e+03,15,9.2526121374972909e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729483905,384521484,1.2192011059274277e+01,729483905,384521484,2.6603321075439453e+01,1.2207031250000000e-03,0.000000e+00,3.037679e-02,-1.905072e+00,3.114786e-01,3.114786e-01,2.711579e-01,2.500000e-01,2.643691e+01,9.971051e-01,5.123872e-01,2.328399e-02,0.000000e+00,2.694491e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.001185e+02,9.358265e+02,15,9.2493813810254597e+00,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729490687,139892578,1.4080989726318254e+01,729490687,139892578,1.4527340888977051e+01,4.8828125000000000e-04,0.000000e+00,3.080126e-01,-2.082243e-01,9.268484e-01,2.328911e-01,3.869233e-01,1.604873e-01,1.461750e+01,7.634810e-01,5.274274e-01,2.540676e-02,0.000000e+00,1.487896e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.473629e+01,1.722163e+02,15,2.0602185114154729e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729490687,140136718,1.4080989793555604e+01,729490687,140136718,1.4534873962402344e+01,4.8828125000000000e-04,0.000000e+00,3.035664e-01,-2.459197e+00,6.280807e-01,3.239271e-01,3.884629e-01,2.244821e-01,1.452107e+01,7.090457e-01,4.300989e-01,2.159080e-02,0.000000e+00,1.482161e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.500169e+01,1.642883e+02,15,2.0738995130612697e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729490687,140869140,1.4080990006476641e+01,729490687,140869140,1.4531057357788086e+01,1.4648437500000000e-03,0.000000e+00,2.501898e-01,-2.981123e-01,7.906842e-01,2.654770e-01,3.876787e-01,1.881783e-01,1.457006e+01,7.355148e-01,4.787632e-01,2.342312e-02,0.000000e+00,1.485023e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.817159e+01,8.008656e+01,15,2.0669266452004429e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729490687,141845703,1.4080990275434322e+01,729490687,141845703,1.4543787956237793e+01,1.7089843750000000e-03,0.000000e+00,2.591820e-01,9.886442e-01,6.274365e-01,3.240005e-01,3.883231e-01,2.245719e-01,1.452978e+01,7.092494e-01,4.300989e-01,2.158968e-02,0.000000e+00,1.483052e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.756543e+01,9.435110e+01,15,2.0726564013909691e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729490687,141845703,1.4080990275434322e+01,729490687,141845703,1.4539974212646484e+01,7.3242187500000000e-04,0.000000e+00,2.794438e-01,2.226041e+00,7.900525e-01,2.654776e-01,3.875397e-01,1.882533e-01,1.457877e+01,7.357170e-01,4.787632e-01,2.342140e-02,0.000000e+00,1.485914e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.626441e+01,1.410123e+02,15,2.0656916038122588e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729490687,143066406,1.4080990611629353e+01,729490687,143066406,1.4553060531616211e+01,1.2207031250000000e-03,0.000000e+00,2.901888e-01,-2.310987e+00,4.464583e-01,4.464583e-01,3.886646e-01,2.500000e-01,1.450851e+01,6.956459e-01,4.030539e-01,2.065094e-02,0.000000e+00,1.482176e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.570005e+01,1.485302e+02,15,2.0756942861591046e+01,0.000000e+00,
         "process:process_id:0","L1","FindChirpSPtwoPN","LSC-AS_Q",729490687,143310546,1.4080990678866705e+01,729490687,143310546,1.4552701950073242e+01,1.4648437500000000e-03,0.000000e+00,2.377280e-01,-2.070064e+00,6.267926e-01,3.240742e-01,3.881835e-01,2.246617e-01,1.453849e+01,7.094530e-01,4.300989e-01,2.158856e-02,0.000000e+00,1.483944e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.914490e+01,4.471184e+01,15,2.0714142985059333e+01,0.000000e+00,