<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE LIGO_LW [
<!ELEMENT LIGO_LW ((LIGO_LW|Comment|Param|Table|Array|Stream|IGWDFrame|AdcData|AdcInterval|Time|Detector)*)>
<!ATTLIST LIGO_LW
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Comment (#PCDATA)>

<!ELEMENT Param (#PCDATA|Comment)*>
<!ATTLIST Param 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED
         Unit CDATA #IMPLIED
         DataUnit CDATA #IMPLIED>

<!ELEMENT Table (Comment?,Column*,Stream?)>
<!ATTLIST Table 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED>

<!ELEMENT Column EMPTY>
<!ATTLIST Column
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Array (Dim*,Stream?)>
<!ATTLIST Array 
         Name CDATA #IMPLIED
         Type CDATA #IMPLIED
         Unit CDATA #IMPLIED>

<!ELEMENT Dim (#PCDATA)>
<!ATTLIST Dim 
         Name  CDATA #IMPLIED
         Unit CDATA #IMPLIED
         Start CDATA #IMPLIED
         Scale CDATA #IMPLIED>

<!ELEMENT Stream (#PCDATA)>
<!ATTLIST Stream 
         Name      CDATA #IMPLIED
         Type      (Remote|Local) "Local"
         Delimiter CDATA ","
         Encoding  CDATA #IMPLIED
         Content   CDATA #IMPLIED>

<!ELEMENT IGWDFrame ((Comment|Param|Time|Detector|AdcData|LIGO_LW|Stream?|Array|IGWDFrame)*)>
<!ATTLIST IGWDFrame 
         Name CDATA #IMPLIED>

<!ELEMENT Detector ((Comment|Param|LIGO_LW)*)>
<!ATTLIST Detector 
         Name CDATA #IMPLIED>

<!ELEMENT AdcData ((AdcData|Comment|Param|Time|LIGO_LW|Array)*)>
<!ATTLIST AdcData 
         Name CDATA #IMPLIED>

<!ELEMENT AdcInterval ((AdcData|Comment|Time)*)>
<!ATTLIST AdcInterval 
         Name CDATA #IMPLIED
         StartTime CDATA #IMPLIED
         DeltaT CDATA #IMPLIED>

<!ELEMENT Time (#PCDATA)>
<!ATTLIST Time 
         Name CDATA #IMPLIED
         Type (GPS|Unix|ISO-8601) "ISO-8601">
]>

<LIGO_LW>
   <Comment>metadata</Comment>
   <Table Name="processgroup:process:table">
      <Column Name="processgroup:process:program" Type="lstring"/>
      <Column Name="processgroup:process:version" Type="lstring"/>
      <Column Name="processgroup:process:cvs_repository" Type="lstring"/>
      <Column Name="processgroup:process:cvs_entry_time" Type="int_4s"/>
      <Column Name="processgroup:process:comment" Type="lstring"/>
      <Column Name="processgroup:process:is_online" Type="int_4s"/>
      <Column Name="processgroup:process:node" Type="lstring"/>
      <Column Name="processgroup:process:username" Type="lstring"/>
      <Column Name="processgroup:process:unix_procid" Type="int_4s"/>
      <Column Name="processgroup:process:start_time" Type="int_4s"/>
      <Column Name="processgroup:process:end_time" Type="int_4s"/>
      <Column Name="processgroup:process:jobid" Type="int_4s"/>
      <Column Name="processgroup:process:domain" Type="lstring"/>
      <Column Name="processgroup:process:ifos" Type="lstring"/>
      <Column Name="processgroup:process:process_id" Type="ilwd:char"/>
      <Stream Name="processgroup:process:table" Type="Local" Delimiter=",">
         "sire","1.15","/usr/local/cvs/lscsoft/lalapps/src/inspiral/sire.c\,v",769623277," ",0,"ldas-grid.ligo.caltech.edu","dbrown",1907,776379204,776379204,0,"lalapps","","process:process_id:0"
      </Stream>
   </Table>
   <Table Name="process_paramsgroup:process_params:table">
      <Column Name="process_paramsgroup:process_params:program" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:process_id" Type="ilwd:char"/>
      <Column Name="process_paramsgroup:process_params:param" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:type" Type="lstring"/>
      <Column Name="process_paramsgroup:process_params:value" Type="lstring"/>
      <Stream Name="process_paramsgroup:process_params:table" Type="Local" Delimiter=",">
         "sire","process:process_id:0","--playground-only","string"," ",
         "sire","process:process_id:0","--input","string","h2-inca_l1h2.files",
         "sire","process:process_id:0","--output","string","h2-inca_l1h2.xml",
         "sire","process:process_id:0","--summary-file","string","h2-inca_l1h2.txt",
         "sire","process:process_id:0","--debug-level","string","33"
      </Stream>
   </Table>
   <Table Name="sngl_inspiralgroup:sngl_inspiral:table">
      <Column Name="sngl_inspiralgroup:sngl_inspiral:process_id" Type="ilwd:char"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ifo" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:search" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:channel" Type="lstring"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:end_time_gmst" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:impulse_time_ns" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:template_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:event_duration" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:amplitude" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eff_distance" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:coa_phase" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass1" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mass2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:mchirp" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:eta" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau2" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau4" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:tau5" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:ttotal" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi0" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:psi3" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:f_final" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:snr" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq" Type="real_4"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:chisq_dof" Type="int_4s"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:sigmasq" Type="real_8"/>
      <Column Name="sngl_inspiralgroup:sngl_inspiral:alpha" Type="real_4"/>
      <Stream Name="sngl_inspiralgroup:sngl_inspiral:table" Type="Local" Delimiter=",">
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729388348,236328125,9.5756846792126691e+00,729388348,236328125,5.1844341278076172e+01,3.1738281250000000e-03,0.000000e+00,7.052581e-02,-3.084851e+00,2.089035e-01,2.089035e-01,1.818611e-01,2.500000e-01,5.144560e+01,1.486700e+00,6.687337e-01,2.660020e-02,0.000000e+00,5.229016e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.194530e+01,1.359608e+02,15,7.0972498071965773e-01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729388348,236816406,9.5756848136915096e+00,729388348,236816406,5.1853469848632812e+01,2.1972656250000000e-03,0.000000e+00,5.639214e-02,-1.352538e+00,2.088815e-01,2.088815e-01,1.818419e-01,2.500000e-01,5.145466e+01,1.486857e+00,6.687808e-01,2.660114e-02,0.000000e+00,5.229934e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.493786e+01,6.259476e+01,15,7.0960031511074950e-01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729388348,237548828,9.5756850154077018e+00,729388348,237548828,5.1862602233886719e+01,1.4648437500000000e-03,0.000000e+00,5.773745e-02,9.151763e-01,2.088594e-01,2.088594e-01,1.818227e-01,2.500000e-01,5.146371e+01,1.487014e+00,6.688280e-01,2.660207e-02,0.000000e+00,5.230850e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.458851e+01,7.079268e+01,15,7.0947516901070673e-01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729388348,238525390,9.5756852955702279e+00,729388348,238525390,5.1871799468994141e+01,1.4648437500000000e-03,0.000000e+00,6.930210e-02,-2.837060e+00,2.088373e-01,2.088373e-01,1.818035e-01,2.500000e-01,5.147277e+01,1.487171e+00,6.688750e-01,2.660301e-02,0.000000e+00,5.231767e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.215301e+01,1.283452e+02,15,7.0935006659167610e-01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729464756,127929687,6.8582095279544593e+00,729464756,127929687,4.7826566696166992e+00,3.1738281250000000e-03,0.000000e+00,1.410532e-01,-1.221742e+00,8.627739e-01,8.627738e-01,7.510883e-01,2.500000e-01,4.839081e+00,3.599749e-01,2.597880e-01,1.657936e-02,0.000000e+00,4.955847e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.973297e+01,1.465966e+02,15,7.7473074387720509e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729464756,128417968,6.8582096624332998e+00,729464756,128417968,4.7911939620971680e+00,2.1972656250000000e-03,0.000000e+00,1.214823e-01,4.526674e-01,8.618702e-01,8.618702e-01,7.503016e-01,2.500000e-01,4.847540e+00,3.603523e-01,2.599696e-01,1.658515e-02,0.000000e+00,4.964508e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.289196e+01,4.373361e+01,15,7.7337883991391214e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729464756,128662109,6.8582097296706506e+00,729464756,128662109,4.7997341156005859e+00,1.2207031250000000e-03,0.000000e+00,1.243409e-01,1.732331e+00,8.609690e-01,8.609689e-01,7.495170e-01,2.500000e-01,4.855999e+00,3.607295e-01,2.601509e-01,1.659094e-02,0.000000e+00,4.973169e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.234618e+01,6.770665e+01,15,7.7203145688855050e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729464756,129150390,6.8582098641494911e+00,729464756,129150390,4.8082780838012695e+00,9.7656250000000000e-04,0.000000e+00,1.479096e-01,-2.924296e+00,8.600703e-01,8.600702e-01,7.487347e-01,2.500000e-01,4.864460e+00,3.611065e-01,2.603321e-01,1.659672e-02,0.000000e+00,4.981831e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.876909e+01,1.925787e+02,15,7.7068881008387873e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,753906250,1.9271722117616900e+01,729509322,753906250,7.3640451431274414e+00,2.9296875000000000e-03,0.000000e+00,9.723096e-02,-1.243808e+00,1.013386e+00,4.530887e-01,5.806575e-01,2.135054e-01,7.431009e+00,4.787992e-01,3.390406e-01,1.930279e-02,0.000000e+00,7.590070e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.254296e+01,1.914345e+02,15,4.8043089785121067e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,754394531,1.9271722252091600e+01,729509322,754394531,7.3729324340820312e+00,1.9531250000000000e-03,0.000000e+00,8.446740e-02,5.303689e-01,1.011577e+00,4.531974e-01,5.802535e-01,2.136706e-01,7.439635e+00,4.790621e-01,3.390406e-01,1.930060e-02,0.000000e+00,7.598957e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.593429e+01,4.841262e+01,15,4.7987381820650334e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,754882812,1.9271722397775285e+01,729509322,754882812,7.3818192481994629e+00,9.7656250000000000e-04,0.000000e+00,9.057692e-02,2.359185e+00,1.009771e+00,4.533070e-01,5.798502e-01,2.138357e-01,7.448260e+00,4.793249e-01,3.390406e-01,1.929843e-02,0.000000e+00,7.607843e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.417098e+01,1.252412e+02,15,4.7931796861989273e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,755126953,1.9271722465016776e+01,729509322,755126953,7.3764653205871582e+00,1.9531250000000000e-03,0.000000e+00,9.737443e-02,3.025836e+00,6.682945e-01,6.682944e-01,5.817841e-01,2.500000e-01,7.407041e+00,4.647307e-01,3.080150e-01,1.805278e-02,0.000000e+00,7.581809e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.254613e+01,1.970471e+02,15,4.8198552044410423e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,755859375,1.9271722666732966e+01,729509322,755859375,7.3851814270019531e+00,1.2207031250000000e-03,0.000000e+00,9.164758e-02,-1.134481e+00,6.678280e-01,6.678280e-01,5.813780e-01,2.500000e-01,7.415665e+00,4.650552e-01,3.081584e-01,1.805698e-02,0.000000e+00,7.590619e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.394106e+01,1.167719e+02,15,4.8142502397135045e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,756103515,1.9271722733970318e+01,729509322,756103515,7.3907094001770020e+00,1.4648437500000000e-03,0.000000e+00,1.044310e-01,-1.025831e+00,1.007968e+00,4.534176e-01,5.794476e-01,2.140008e-01,7.456886e+00,4.795876e-01,3.390406e-01,1.929626e-02,0.000000e+00,7.616729e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.095227e+01,2.225876e+02,15,4.7876358826934222e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,756835937,1.9271722935686508e+01,729509322,756835937,7.3938927650451660e+00,1.4648437500000000e-03,0.000000e+00,9.128600e-02,1.366786e+00,6.673625e-01,6.673625e-01,5.809727e-01,2.500000e-01,7.424290e+00,4.653797e-01,3.083017e-01,1.806118e-02,0.000000e+00,7.599429e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.402192e+01,1.019468e+02,15,4.8086586006153471e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,757568359,1.9271723137402699e+01,729509322,757568359,7.4026112556457520e+00,1.4648437500000000e-03,0.000000e+00,1.017809e-01,-2.788724e+00,6.668977e-01,6.668977e-01,5.805682e-01,2.500000e-01,7.432914e+00,4.657040e-01,3.084449e-01,1.806538e-02,0.000000e+00,7.608239e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.153246e+01,2.097956e+02,15,4.8030789204153530e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729509322,759521484,1.9271723686522908e+01,729509322,759521484,7.4113230705261230e+00,2.6855468750000000e-03,0.000000e+00,1.239212e-01,1.083876e+00,6.664339e-01,6.664338e-01,5.801644e-01,2.500000e-01,7.441539e+00,4.660282e-01,3.085880e-01,1.806957e-02,0.000000e+00,7.617049e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.767513e+01,3.436898e+02,15,4.7975108574307175e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,989746093,6.3248566719806854e-01,729700896,989746093,7.6779966354370117e+00,4.6386718750000000e-03,0.000000e+00,1.581046e-01,-1.476508e+00,9.134228e-01,4.744538e-01,5.670865e-01,2.249904e-01,7.729754e+00,4.855077e-01,3.337688e-01,1.901429e-02,0.000000e+00,7.900507e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.309955e+01,1.084961e+02,15,4.2894530205120898e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,989990234,6.3248573443541922e-01,729700896,989990234,7.6871886253356934e+00,2.9296875000000000e-03,0.000000e+00,1.416866e-01,-2.735653e-01,9.116082e-01,4.746670e-01,5.666938e-01,2.251637e-01,7.738684e+00,4.857764e-01,3.337688e-01,1.901240e-02,0.000000e+00,7.909704e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.460903e+01,7.240366e+01,15,4.2845045673851034e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,990722656,6.3248594735645580e-01,729700896,990722656,7.6963887214660645e+00,2.4414062500000000e-03,0.000000e+00,1.297058e-01,1.895909e+00,9.097953e-01,4.748820e-01,5.663018e-01,2.253369e-01,7.747613e+00,4.860449e-01,3.337688e-01,1.901052e-02,0.000000e+00,7.918900e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.594925e+01,3.276463e+01,15,4.2795653168450531e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,990966796,6.3248601459794573e-01,729700896,990966796,7.6935887336730957e+00,2.9296875000000000e-03,0.000000e+00,1.449386e-01,6.252514e-01,6.518599e-01,6.518598e-01,5.674769e-01,2.500000e-01,7.720892e+00,4.764474e-01,3.131706e-01,1.820324e-02,0.000000e+00,7.902372e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.429769e+01,7.187541e+01,15,4.2943770391841074e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,991455078,6.3248614907264711e-01,729700896,991455078,7.7055816650390625e+00,1.9531250000000000e-03,0.000000e+00,1.303146e-01,-2.182819e+00,9.079843e-01,4.750989e-01,5.659105e-01,2.255100e-01,7.756544e+00,4.863133e-01,3.337688e-01,1.900864e-02,0.000000e+00,7.928097e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.586560e+01,4.183818e+01,15,4.2746378075366112e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,991699218,6.3248621631413693e-01,729700896,991699218,7.7026119232177734e+00,2.4414062500000000e-03,0.000000e+00,1.326027e-01,2.681667e+00,6.514080e-01,6.514079e-01,5.670835e-01,2.500000e-01,7.729821e+00,4.767779e-01,3.133154e-01,1.820745e-02,0.000000e+00,7.911491e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.561876e+01,4.094539e+01,15,4.2894158928337616e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,991943359,6.3248628355148762e-01,729700896,991943359,7.7147750854492188e+00,1.4648437500000000e-03,0.000000e+00,1.485331e-01,-4.317787e-01,9.061750e-01,4.753178e-01,5.655200e-01,2.256830e-01,7.765473e+00,4.865817e-01,3.337688e-01,1.900677e-02,0.000000e+00,7.937293e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.391159e+01,1.043232e+02,15,4.2697236261126976e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,992187500,6.3248635078883830e-01,729700896,992187500,7.7116360664367676e+00,1.7089843750000000e-03,0.000000e+00,1.280294e-01,-1.872549e+00,6.509569e-01,6.509569e-01,5.666909e-01,2.500000e-01,7.738750e+00,4.771083e-01,3.134601e-01,1.821165e-02,0.000000e+00,7.920610e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.616734e+01,3.319793e+01,15,4.2844668050456072e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729700896,992675781,6.3248648526767892e-01,729700896,992675781,7.7206587791442871e+00,1.2207031250000000e-03,0.000000e+00,1.464135e-01,-1.313796e-01,6.505066e-01,6.505066e-01,5.662989e-01,2.500000e-01,7.747680e+00,4.774385e-01,3.136047e-01,1.821586e-02,0.000000e+00,7.929729e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.412918e+01,1.000838e+02,15,4.2795291411584770e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729853641,291748046,1.9177625133035082e+01,729853641,291748046,4.0192289352416992e+00,2.4414062500000000e-03,0.000000e+00,1.495561e-01,-2.159279e+00,9.554089e-01,9.554088e-01,8.317317e-01,2.500000e-01,4.082653e+00,3.250723e-01,2.427118e-01,1.602521e-02,0.000000e+00,4.181038e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.510823e+01,1.365296e+02,15,1.4100687282222447e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729853641,291992187,1.9177625200276573e+01,729853641,291992187,4.0278534889221191e+00,1.7089843750000000e-03,0.000000e+00,1.377519e-01,-1.023115e+00,9.542110e-01,9.542109e-01,8.306889e-01,2.500000e-01,4.091198e+00,3.254803e-01,2.429149e-01,1.603191e-02,0.000000e+00,4.189795e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.723132e+01,5.662684e+01,15,1.4071233590781013e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729853641,292480468,1.9177625334755415e+01,729853641,292480468,4.0364718437194824e+00,1.2207031250000000e-03,0.000000e+00,1.400777e-01,6.556256e-01,9.530171e-01,9.530171e-01,8.296496e-01,2.500000e-01,4.099743e+00,3.258881e-01,2.431177e-01,1.603860e-02,0.000000e+00,4.198553e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.675125e+01,6.647697e+01,15,1.4041905520231655e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729853641,292968750,1.9177625469230115e+01,729853641,292968750,4.0450978279113770e+00,9.7656250000000000e-04,0.000000e+00,1.556478e-01,2.253594e+00,9.518272e-01,9.518271e-01,8.286136e-01,2.500000e-01,4.108289e+00,3.262955e-01,2.433203e-01,1.604529e-02,0.000000e+00,4.207310e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.405016e+01,1.727418e+02,15,1.4012695357010825e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729860083,921875000,2.0972144413333801e+01,729860083,921875000,7.7364573478698730e+00,1.4648437500000000e-03,0.000000e+00,4.361945e-01,2.536513e+00,9.351671e-01,4.606012e-01,5.643726e-01,2.210994e-01,7.791803e+00,4.894010e-01,3.383612e-01,1.918885e-02,0.000000e+00,7.962032e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.341166e+00,5.302004e+01,15,1.0253933674181416e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729860083,922119140,2.0972144480571149e+01,729860083,922119140,7.7452659606933594e+00,1.4648437500000000e-03,0.000000e+00,3.865514e-01,-2.639109e+00,9.334774e-01,4.607605e-01,5.640012e-01,2.212612e-01,7.800356e+00,4.896573e-01,3.383612e-01,1.918695e-02,0.000000e+00,7.970839e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.279419e+00,4.053550e+01,15,1.0242690762687745e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729860083,922607421,2.0972144626254838e+01,729860083,922607421,7.7540712356567383e+00,7.3242187500000000e-04,0.000000e+00,3.664369e-01,-9.361505e-01,9.317898e-01,4.609210e-01,5.636305e-01,2.214229e-01,7.808909e+00,4.899135e-01,3.383612e-01,1.918507e-02,0.000000e+00,7.979646e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.729109e+00,3.293969e+01,15,1.0231472320565482e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729860083,923095703,2.0972144760733677e+01,729860083,923095703,7.7628803253173828e+00,4.8828125000000000e-04,0.000000e+00,4.138381e-01,8.057231e-01,9.301041e-01,4.610828e-01,5.632604e-01,2.215846e-01,7.817462e+00,4.901695e-01,3.383612e-01,1.918318e-02,0.000000e+00,7.988454e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.725040e+00,4.976935e+01,15,1.0220275289143199e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729860083,923339843,2.0972144827971029e+01,729860083,923339843,7.7582063674926758e+00,7.3242187500000000e-04,0.000000e+00,3.750816e-01,5.141301e-02,6.486418e-01,6.486418e-01,5.646755e-01,2.500000e-01,7.784839e+00,4.788111e-01,3.142055e-01,1.823330e-02,0.000000e+00,7.967678e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.541099e+00,3.764721e+01,15,1.0263108923791195e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",729860083,923828125,2.0972144962449867e+01,729860083,923828125,7.7668499946594238e+00,4.8828125000000000e-04,0.000000e+00,3.828823e-01,1.746789e+00,6.482146e-01,6.482146e-01,5.643036e-01,2.500000e-01,7.793391e+00,4.791267e-01,3.143435e-01,1.823730e-02,0.000000e+00,7.976412e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.362493e+00,4.110355e+01,15,1.0251843072261829e+01,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,128906250,1.7118802265069551e+01,730190906,128906250,1.8877340316772461e+01,3.6621093750000000e-03,0.000000e+00,9.587996e-02,-1.796608e+00,7.834050e-01,2.014974e-01,3.313408e-01,1.627307e-01,1.892880e+01,8.886804e-01,5.800234e-01,2.656003e-02,0.000000e+00,1.926402e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.545373e+01,2.239018e+02,15,2.1954437435391476e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,129882812,1.7118802534023093e+01,730190906,129882812,1.8885890960693359e+01,2.9296875000000000e-03,0.000000e+00,8.656102e-02,6.144560e-01,7.829783e-01,2.014883e-01,3.312528e-01,1.627787e-01,1.893718e+01,8.888557e-01,5.800234e-01,2.655827e-02,0.000000e+00,1.927257e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.711365e+01,1.800803e+02,15,2.1944724837137328e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,130859375,1.7118802802980774e+01,730190906,130859375,1.8894445419311523e+01,2.6855468750000000e-03,0.000000e+00,8.413891e-02,3.035089e+00,7.825519e-01,2.014792e-01,3.311649e-01,1.628267e-01,1.894556e+01,8.890309e-01,5.800234e-01,2.655652e-02,0.000000e+00,1.928112e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.760241e+01,1.720982e+02,15,2.1935018204852628e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,131347656,1.7118802937455474e+01,730190906,131347656,1.8901077270507812e+01,2.6855468750000000e-03,0.000000e+00,8.992881e-02,1.484703e-01,6.999795e-01,2.206845e-01,3.315080e-01,1.822447e-01,1.891288e+01,8.660250e-01,5.417365e-01,2.506750e-02,0.000000e+00,1.926224e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.648333e+01,1.960945e+02,15,2.1972914042758238e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,132324218,1.7118803217618002e+01,730190906,132324218,1.8903007507324219e+01,2.9296875000000000e-03,0.000000e+00,8.073194e-02,-1.061428e-01,7.821259e-01,2.014701e-01,3.310770e-01,1.628747e-01,1.895394e+01,8.892062e-01,5.800234e-01,2.655476e-02,0.000000e+00,1.928968e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.834119e+01,1.531868e+02,15,2.1925319527193849e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,133056640,1.7118803419334192e+01,730190906,133056640,1.8909643173217773e+01,2.9296875000000000e-03,0.000000e+00,8.417419e-02,-2.675433e+00,6.995742e-01,2.206819e-01,3.314199e-01,1.822985e-01,1.892126e+01,8.662002e-01,5.417365e-01,2.506606e-02,0.000000e+00,1.927080e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.760633e+01,1.738756e+02,15,2.1963179569282798e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,133056640,1.7118803419334192e+01,730190906,133056640,1.8911554336547852e+01,2.9296875000000000e-03,0.000000e+00,7.915701e-02,1.946479e+00,7.817004e-01,2.014610e-01,3.309892e-01,1.629227e-01,1.896232e+01,8.893813e-01,5.800234e-01,2.655301e-02,0.000000e+00,1.929823e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.870198e+01,1.353961e+02,15,2.1915632781473962e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,133544921,1.7118803553813034e+01,730190906,133544921,1.8920110702514648e+01,2.6855468750000000e-03,0.000000e+00,8.009028e-02,-2.738076e+00,7.812751e-01,2.014519e-01,3.309015e-01,1.629707e-01,1.897070e+01,8.895565e-01,5.800234e-01,2.655126e-02,0.000000e+00,1.930678e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.847997e+01,1.308048e+02,15,2.1905942058441110e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,133789062,1.7118803621050386e+01,730190906,133789062,1.8928665161132812e+01,1.9531250000000000e-03,0.000000e+00,7.962307e-02,-1.581187e+00,7.808502e-01,2.014429e-01,3.308138e-01,1.630187e-01,1.897908e+01,8.897316e-01,5.800234e-01,2.654951e-02,0.000000e+00,1.931534e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.858430e+01,1.147570e+02,15,2.1896275199286030e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,134033203,1.7118803688291873e+01,730190906,134033203,1.8918199539184570e+01,2.6855468750000000e-03,0.000000e+00,7.574789e-02,-2.295173e-01,6.991693e-01,2.206794e-01,3.313318e-01,1.823523e-01,1.892965e+01,8.663754e-01,5.417365e-01,2.506463e-02,0.000000e+00,1.927935e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.956054e+01,1.091142e+02,15,2.1953455039089764e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,134765625,1.7118803890008067e+01,730190906,134765625,1.8926753997802734e+01,2.4414062500000000e-03,0.000000e+00,7.511067e-02,1.858223e+00,6.987646e-01,2.206769e-01,3.312438e-01,1.824062e-01,1.893803e+01,8.665505e-01,5.417365e-01,2.506320e-02,0.000000e+00,1.928791e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.972213e+01,1.013394e+02,15,2.1943742440835621e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,135498046,1.7118804102929101e+01,730190906,135498046,1.8930082321166992e+01,2.9296875000000000e-03,0.000000e+00,7.697088e-02,-8.451494e-01,6.079704e-01,2.481538e-01,3.316306e-01,2.058400e-01,1.890123e+01,8.442802e-01,5.034497e-01,2.365303e-02,0.000000e+00,1.926572e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.926421e+01,1.112037e+02,15,2.1986462759364600e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,135498046,1.7118804102929101e+01,730190906,135498046,1.8935302734375000e+01,2.4414062500000000e-03,0.000000e+00,7.733715e-02,-2.373253e+00,6.983603e-01,2.206744e-01,3.311559e-01,1.824600e-01,1.894641e+01,8.667256e-01,5.417365e-01,2.506177e-02,0.000000e+00,1.929646e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.915010e+01,1.239275e+02,15,2.1934029842581477e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,135742187,1.7118804170170591e+01,730190906,135742187,1.8943868637084961e+01,1.9531250000000000e-03,0.000000e+00,7.849810e-02,-1.220473e+00,6.979564e-01,2.206719e-01,3.310680e-01,1.825138e-01,1.895479e+01,8.669007e-01,5.417365e-01,2.506034e-02,0.000000e+00,1.930502e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.886271e+01,1.270867e+02,15,2.1924329176266220e+00,0.000000e+00,
         "process:process_id:0","H2","FindChirpSPtwoPN","LSC-AS_Q",730190906,136474609,1.7118804371886782e+01,730190906,136474609,1.8938650131225586e+01,2.6855468750000000e-03,0.000000e+00,7.103485e-02,1.650876e+00,6.075768e-01,2.481677e-01,3.315424e-01,2.059009e-01,1.890962e+01,8.444560e-01,5.034497e-01,2.365193e-02,0.000000e+00,1.927427e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.086939e+01,6.837989e+01,15,2.1976704422011388e+00,0.000000e+00,